### PR TITLE
fix: can't modify display attributes of non-wing constructs

### LINKED ISSUE #6629: Cannot modify Wing Console display attributes of classes extending non-Wing constructs
### I tried this:

```js
bring "cdktf" as cdktf;
bring cloud;

class Foo extends cdktf.TerraformOutput {
  new() {
    super();
    nodeof(this).hidden = true;
  }
}

new Foo();
```

### This happened:

When I run "wing run" I see "Foo" as a node

### I expected this:

I expected the node to be hidden

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

0.74.12

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by eladcon**
Fixes #6629 

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingsdk/src/core/tree.ts [hunk 1]
```diff
@@ -220,14 +220,7 @@ export function synthesizeTree(app: App, outdir: string) {
   );
 }
 
-function isIResource(construct: IConstruct): construct is IResource {
```
Comment (eladb) [inline libs/wingsdk/src/core/tree.ts:223]: Love it!

Best fix ever

**Review by eladb — APPROVED** [review]
