### PR TITLE
fix(cli): breaks without globally installed aws-cdk-lib

### LINKED ISSUE #3396: CLI breaks without globally install aws-cdk-lib
### I tried this:

```
wing test main.w
```

or 

```
wing compile -t tf-aws main.w
```

### This happened:

```
Error: Cannot find module 'aws-cdk-lib'
Require stack:
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-awscdk/app.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-awscdk/index.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/index.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/index.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/test.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/cli.js
- /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/bin/wing
    at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
    at Module._load (node:internal/modules/cjs/loader:920:27)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-awscdk/app.js:32:26)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-awscdk/index.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.js:6:25)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/index.js:17:14)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/index.js:33:28)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at Object.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/test.js:33:15)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at /Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/cli.js:49:112
    at async Command.<anonymous> (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/cli.js:49:30) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-awscdk/app.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/target-awscdk/index.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/function.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/shared-aws/index.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/node_modules/@winglang/sdk/lib/index.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/test.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/cli.js',
    '/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/bin/wing'
  ]
}
```

### I expected this:

No error

### Is there a workaround?

Downgrade to `0.24.14`

### Component

CLI

### Wing Version

0.24.15

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #3396

This "instanceof" check is causing problems since it results in several other modules to get imported, including those that require `aws-cdk-lib` to be installed -- even if you're not compiling to the `awscdk` target. Removing this code path as a hotfix.

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://www.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Review by MarkMcCulloh — APPROVED** [review]

**Review by hasanaburayyan — APPROVED** [review]
Any idea why the above instanceof check (for  TfAwsFunction) does not cause a similar issue?

**Comment by MarkMcCulloh** [comment]
> Any idea why the above instanceof check (for TfAwsFunction) does not cause a similar issue?

cdktf is a bundled dependency of @winglang/sdk so it's included in the end package. 
aws-cdk-lib is also supposed to be bundled, but we intentionally remove it from the final package (because it's took big iirc)

File: libs/wingsdk/src/shared-aws/function.ts [hunk 1]
```diff
@@ -35,10 +34,6 @@ export class Function {
       return host;
     }
 
-    if (host instanceof AwsCdkFunction) {
```
Comment (eladb) [inline libs/wingsdk/src/shared-aws/function.ts:38]: I think duck-typing much be a better approach here.

Basically check that the host implements `IAwsFunction`'s methods.
