### PR TITLE
fix(sdk): functions and services are never updated in the simulator

### LINKED ISSUE #6116: `simulator.update()` doesn't reflect changes in functions
### I tried this:

In https://github.com/winglang/wing/pull/6069, the Console starts using the new `simulator.update()` method from the Simulator.

### This happened:

Using the `simulator.update()` method lead to a bug where new changes in functions weren't available anymore.

### I expected this:

The function code should be up to date in the Console instance after a call to `simulator.update()`

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by eladb**
Fixes #6116 by allowing a simulator resource to determine it's update "plan" when new configuration arrives.

For now, both `cloud.Function` and `cloud.Service` always return "REPLACE" which means that these resources will always get updated. In a future commit we can be more granular about the update by calculating the bundle hash.

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Docs updated (only required for features)
- [x] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingsdk/src/simulator/simulator.ts [hunk 1]
```diff
@@ -920,6 +1007,36 @@ export interface ISimulatorResourceInstance {
...
+
+  /**
+   * Determines the update plan for applying a new configuration for this resource.
+   *
+   * If this is not implemented, the default behavior is to automatically replace the resource if
+   * the new configuration is different from the current configuration.
+   *
+   * @param newConfig The new configuration to apply
+   */
+  plan(newConfig: BaseResourceSchema): Promise<UpdatePlan>;
```
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/simulator.ts:1019]: Is the resource receiving a piece of config with all tokens resolved, or is it possible there are unresolved tokens in it? Which do you think should be the contract here?

**Review by Chriscbr — APPROVED** [review]

File: libs/wingsdk/src/simulator/simulator.ts (hunk 1 above)
Comment (eladb) [reply libs/wingsdk/src/simulator/simulator.ts:1019]: Tokens are unresolved, which I think is reasonable. Added to the docs.
