### PR TITLE
fix(sdk): permissions errors are not caught in simulator

### LINKED ISSUE #6002: sim resource should throw exception when operation was not lifted
### Use Case

As part of our guarantee that `if it works on your machine it works on the cloud` we have introduced a runtime error when a host is accessing an un-lifted operation. 

# Consider the following code

### `main.w`
```wing
bring cloud;
bring util;

let b = new cloud.Bucket();

class C {
  extern "./ex.ts" inflight pub static _writeToBucket(b: cloud.Bucket, file: str, content: str): void;
}
let liftAndWrite = new cloud.Function(inflight () => {
  lift(b, ["put"]);
  C._writeToBucket(b, "file.txt", "hello wing");
  }) as "liftAndWrite";
  
let justWrite = new cloud.Function(inflight () => {
  C._writeToBucket(b, "file.txt", "hello wing");
}) as "justWrite";

test "liftAndWrite should work" {
  liftAndWrite.invoke();
  util.waitUntil(() => {
    return b.exists("file.txt");
  }, timeout: 10s);
  assert(b.exists("file.txt"));
}

test "justWrite should not work" {
  justWrite.invoke();
  util.waitUntil(() => {
    return b.exists("file.txt");
  }, timeout: 10s);
  assert(!b.exists("file.txt"));
}
```
### `ex.ts`
```ts
import type extern from "./ex.extern";

export const _writeToBucket: extern["_writeToBucket"] = async (b, file, content) => {
  try {
    await b.put(file, content);
  } catch {
    
  }
}
```

## Testing on AWS 
```sh
% wing test  -t tf-aws main.w
✔ Compiling main.w to tf-aws...

✔ terraform init

✔ terraform apply

✔ Setting up test runner...

✔ Running tests...

pass ─ main.tfaws.630318 » root/Test.m4-Gz3rJlJ/env0/test:liftAndWrite should work 
pass ─ main.tfaws.630318 » root/Test.m4-Gz3rJlJ/env1/test:justWrite should not work
✔ terraform destroy

 
 
Tests 2 passed (2)
Test Files 1 passed (1)
Duration 1m43.62s
```
## Testing on sim
```sh
% wing test  main.w          
pass ─ main.wsim » root/env0/test:liftAndWrite should work 
fail ┌ main.wsim » root/env1/test:justWrite should not work
     │ Error: assertion failed: !b.exists("file.txt")
     │    --> main.w:31:3
     │    | util.waitUntil(() => {
     │    |   return b.exists("file.txt");
     │    | }, timeout: 10s);
     │ 31 | assert(!b.exists("file.txt"));
     │    | ^
     └ at handle /private/tmp/ts/main.w:31:3
 
 
Tests 1 failed | 1 passed (2)
Test Files 1 failed (1)
Duration 0m0.81s
```

### Proposed Solution

Throw an exception when an operation is not lifted in sim

### Implementation Notes

_No response_

### Component

Compiler, SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

### PR DESCRIPTION
**Pull request by Chriscbr**
Reintroduce https://github.com/winglang/wing/pull/6079 after it was reverted by https://github.com/winglang/wing/pull/6125 in an attempt to fix https://github.com/winglang/wing/issues/6135.

Fixes #6002

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingsdk/src/target-sim/app.ts [hunk 1]
```diff
@@ -137,6 +143,9 @@ export class App extends core.App {
       case SERVICE_FQN:
         return require.resolve("./service.inflight");
 
+      case SERVICE_HELPER_FQN:
```
Comment (eladb) [inline libs/wingsdk/src/target-sim/app.ts:146]: Why are we reintroducing this? Don't you want to merge this change with the inline policy stuff?

**Review by eladb — CHANGES_REQUESTED** [review]

File: libs/wingsdk/src/target-sim/app.ts (hunk 1 above)
Comment (Chriscbr) [reply libs/wingsdk/src/target-sim/app.ts:146]: This is an implementation detail (it's an internal resource)

Comment (eladb) [reply libs/wingsdk/src/target-sim/app.ts:146]: I see. I was thinking that if you are already reintroducing this PR than it made sense to just combine them together.

**Review by eladb — APPROVED** [review]
