### PR TITLE
fix: unable to `wing run` a file in a different directory

### LINKED ISSUE #1467: wing it doesn't work with wsim file
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

a.w
```ts (wing)
bring cloud;
```

```sh
wing compile --target sim a.w
wing it target/a.wsim
```

### I expected this:

to work

### Instead, this happened:

```sh
% wing it target/a.wsim
/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/dist/commands/run.js:18
        throw new Error(simfile + " doesn't exist");
              ^

Error: target/a.wsim doesn't exist
    at Command.run (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/dist/commands/run.js:18:15)
    at Command.listener [as _actionHandler] (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:482:17)
    at /Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1283:65
    at Command._chainOrCall (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1177:12)
    at Command._parseCommand (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1283:27)
    at /Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1081:27
    at Command._chainOrCall (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1177:12)
    at Command._dispatchSubcommand (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1077:23)
    at Command._parseCommand (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:1248:19)
    at Command.parse (/Users/eyalkeren/.nvm/versions/node/v18.4.0/lib/node_modules/winglang/node_modules/commander/lib/command.js:909:10)
```

### Component:

Compiler

### Wing Version:

0.5.10

### Node.js Version:

_No response_

### Platform(s):

MacOS

### Anything else?

- [ ] The problem is that the code looses the full path, once I tweaked the code (`node_modules/winglang/dist/commands/run.js`) to have the full path, it worked

- [ ] wing command also corrupts the terminal, if you run wing compile command and after try to do stuff like arrow-up/arrow-down you on the next prompt I get `^[[A` instead of browsing my command line history. This is solved by Ctrl-C

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #1467

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: apps/wing/src/commands/run.ts [hunk 1]
```diff
@@ -1,21 +1,23 @@
...
         }
         simfile = wingFiles[0];
-    } else if (!wingFiles.includes(simfile)) {
+    }
+    
+    if (!existsSync(simfile)) {
         throw new Error(simfile + " doesn't exist");
     }
 
     simfile = normalPath(resolve(simfile));
```
Comment (staycoolcall911) [inline apps/wing/src/commands/run.ts:20]: don't you need to normalize the path before checking `!existsSync()`? I mean, will `existsSync()` work cross platform if it runs on simFile path that has not been normalized?

**Review by staycoolcall911 — APPROVED** [review]
Added 1 comment, other than that LGTM

File: apps/wing/src/commands/run.ts (hunk 1 above)
Comment (MarkMcCulloh) [reply apps/wing/src/commands/run.ts:20]: existsSync() uses platform-specific logic, so yeah it'll work without normalization
