### PR TITLE
fix: missing completions in if-statement condition

### LINKED ISSUE #2374: Invalid completion inside an if statement (vscode)
### I tried this:

See video

@ekeren additional info:
```ts (wing)
let a = MutMap<str> {};
let removeThisLineToFixIssue = MutMap<str> {"a": "b"};

if a.
// .. ^ autocomplete does not work because of line 2 
// (the fact that we have  {"a": "b"} seems to break stuff)
```

### This happened:

https://user-images.githubusercontent.com/598796/235889844-7b8a3bae-626d-4ea7-9fc6-b2e067c84d5c.mov

### I expected this:

To see the completion for the map api

### Is there a workaround?

_No response_

### Component

IDE Extension

### Wing Version

0.15.4

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #2374

### Problem

tree-sitter is unable to recognize the following if-statement:

```
let a = MutMap<str> {};
if a.
```

due to missing at least a `{` to start off a block. This means the entire statement becomes an error, causing the reference inside the condition to get thrown away and unavailable to the compiler/lsp.

### Solution

The idea here is to have something similar to the automatic semicolon insertion, but for blocks instead. This means tree-sitter will automatically insert an empty block `{}` when one is expected but unavailable. Like the auto semicolon, this still results in a parse error but we still create a useful AST.

This not only solves the problem for if-statements, but other similar syntactic structures like for-loops.

- [x] PR title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] PR description explains motivation and solution
- [x] Tests added
- [ ] Docs updated
- [ ] Needs end-to-end tests (`pr/e2e-full` label)

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/tree-sitter-wing/src/scanner.c [hunk 1]
```diff
@@ -150,6 +151,42 @@ static bool scan_automatic_semicolon(TSLexer *lexer)
   return true;
 }
 
+/**
+ * Check if an automatic empty block ( `{}` ) could be inserted
+ *
+ * @return true if an automatic block was found (aka "inserted"), false otherwise
+ */
+static bool scan_automatic_block(TSLexer *lexer)
+{
```
Comment (Chriscbr) [inline libs/tree-sitter-wing/src/scanner.c:160]: I have no idea how the tree sitter parser works but it looks dope. Would be cool to learn more about it in a team time or something 😄

**Review by Chriscbr — APPROVED** [review]
Very nice
