### PR TITLE
fix: mac preopen only root device

### LINKED ISSUE #2370: `wing` cli requests access to a network volume?
### I tried this:

Run the CLI

### This happened:

Something that looks like this (but with `wing`):

Screenshot 2023-05-03 at 8 25 54

### I expected this:

I don't see why we need this

### Is there a workaround?

_No response_

### Component

CLI

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

I suspect this is related to this https://github.com/winglang/wing/pull/2323

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by eladcon**
Preopen only directories on the root device when running on mac

Fixes #2370 

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: apps/wing/src/wingc.ts [hunk 1]
```diff
@@ -108,14 +108,21 @@ export async function load(options: WingCompilerLoadOptions) {
   } else {
     // mapping the root is not sufficient on linux/mac
     // we need to also map all directories in the root
+    const rootStat = await fs.promises.stat("/");
```
Comment (MarkMcCulloh) [inline apps/wing/src/wingc.ts:111]: nit: to avoid toString later

```suggestion
    const rootDeviceId = await fs.promises.stat("/").then((stat) => stat.dev.toString);
```

**Review by MarkMcCulloh — APPROVED** [review]
