### PR TITLE
fix: missing a semicolon hurts parser error recovery and missing lsp completions

### LINKED ISSUE #2025: IDE completions are not working within inflight methods
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I tried to type this code in my IDE:

```js
bring cloud;

resource Foo {
  my_bucket: cloud.Bucket;
  init() {}
  
  inflight foo() {
    this.my_bucket.put("hello.txt", "world");
  }
}
```

### I expected this:

I expected that when I typed `this.`, I would see `my_bucket` as a possible completion, and then when I typed `this.my_bucket.` I would see the `cloud.Bucket`'s inflight API as a list of completions.

### Instead, this happened:

https://user-images.githubusercontent.com/598796/230865996-fb028a86-8b4c-4cd4-8886-e51a4cb23e31.mov

### Is there a workaround?

N/A

### Component:

IDE Extension

### Wing Version:

0.8.47

### Node.js Version:

_No response_

### Platform(s):

_No response_

### Anything else?

_No response_

### LINKED ISSUE #2123: Compiler panic when parsing incomplete Json expr
### I tried this

```
bring cloud;

let api = new cloud.Api();
api.get("/test", inflight (req: cloud.ApiRequest): cloud.ApiResponse => {
  return cloud.ApiResponse {
    status: 200,
    body: Json 
  }
});
```

### I expected this:

Parsing errors / no VS code extension crash

### Instead, this happened

Compiler panic / VS code extension crash

### Is there a workaround?

_No response_

### Component

Compiler, IDE Extension

### Wing Version

0.12.6

### Wing Console Version

_No response_

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
fixes #2123
fixes #2025

## Overall Goals
- Improve parser error recovery, with an emphasis on incomplete statements missing `;`
- Help LSP get better completions for nested identifiers

### Before
image

### After
image

---

### Grammar changes

- added an external scanner that automatically inserts semicolons
- added some aliases for identifier usage. This isn't super important, but it helps with grammar debugging because it distinguishes between an identifier used in a type vs once used in a nested expression
- other minor cleanup
- added some convenience scripts to dev the grammar a little easier

### Parser changes
- support the grammar changes
- avoided a couple panics
- better handling of incomplete Json
- better handling of incomplete reference to make sure some usable data makes it into the AST

### LSP changes
- improve the logic to find the type we're completing
  - still can't handle completions for nested method calls (e.g. `a.b().`)

### misc changes

- Removed `.`s from compiler error messages. Most of them didn't have it and IMO I think it looks better without

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/tree-sitter-wing/tree-sitter-dsl.d.ts [hunk 1]
```diff
@@ -0,0 +1,371 @@
...
+  BaseGrammarRuleName extends string = never,
+  Rules extends RuleBuilders<RuleName, BaseGrammarRuleName> = RuleBuilders<
+    RuleName,
+    BaseGrammarRuleName
+  >
+> {
+  /**
+   * Name of the grammar language.
+   */
+  name: string;
```
Comment (eladb) [inline libs/tree-sitter-wing/tree-sitter-dsl.d.ts:67]: ooo lala!

File: libs/tree-sitter-wing/src/scanner.c [hunk 2]
```diff
@@ -0,0 +1,116 @@
...
+void *tree_sitter_wing_external_scanner_create() { return NULL; }
+void tree_sitter_wing_external_scanner_destroy(void *p) {}
+void tree_sitter_wing_external_scanner_reset(void *p) {}
+unsigned tree_sitter_wing_external_scanner_serialize(void *p, char *buffer) { return 0; }
+void tree_sitter_wing_external_scanner_deserialize(void *p, const char *b, unsigned n) {}
+
+// static void advance(TSLexer *lexer) { lexer->advance(lexer, false); }
+static void skip(TSLexer *lexer) { lexer->advance(lexer, true); }
+
+static bool scan_whitespace_and_comments(TSLexer *lexer) {
```
Comment (eladb) [inline libs/tree-sitter-wing/src/scanner.c:19]: can you add a comment on each method to describe what it's doing?

File: libs/tree-sitter-wing/src/scanner.c [hunk 3]
```diff
@@ -0,0 +1,116 @@
+// Adapted from https://github.com/tree-sitter/tree-sitter-javascript/blob/master/src/scanner.c
```
Comment (eladb) [inline libs/tree-sitter-wing/src/scanner.c:1]: What's the delta between the javascript scanner and this one?

File: libs/tree-sitter-wing/project.json [hunk 4]
```diff
@@ -27,6 +27,20 @@
           "command": "cargo wasi build --release"
         }
       }
+    },
+    "dev": {
```
Comment (eladb) [inline libs/tree-sitter-wing/project.json:31]: 🙏

File: libs/tree-sitter-wing/grammar.js [hunk 5]
```diff
@@ -239,7 +250,7 @@ module.exports = grammar({
     for_in_loop: ($) =>
       seq(
         "for",
-        field("iterator", $.reference),
+        field("iterator", $.identifier),
```
Comment (eladb) [inline libs/tree-sitter-wing/grammar.js:253]: dah!

File: libs/tree-sitter-wing/grammar.js [hunk 6]
```diff
@@ -24,44 +24,54 @@ module.exports = grammar({
...
-  ],
+  conflicts: ($) => [[$._reference_identifier, $._type_identifier]],
 
   supertypes: ($) => [$.expression, $._literal],
 
   rules: {
     // Basics
     source: ($) => repeat($._statement),
     block: ($) => seq("{", optional(repeat($._statement)), "}"),
+    _semicolon: ($) => choice(";", $.AUTOMATIC_SEMICOLON),
```
Comment (eladb) [inline libs/tree-sitter-wing/grammar.js:44]: Curious, why `_`? (feels unnecessarily apologetic)

File: libs/tree-sitter-wing/grammar.js [hunk 7]
```diff
@@ -24,44 +24,54 @@ module.exports = grammar({
...
+      choice(
+        $.nested_identifier,
+        $._reference_identifier,
+        $.structured_access_expression
+      ),
 
     identifier: ($) => /([A-Za-z_$][A-Za-z_$0-9]*|[A-Z][A-Z0-9_]*)/,
+    _type_identifier: ($) => alias($.identifier, $.type_identifier),
+    _member_identifier: ($) => alias($.identifier, $.member_identifier),
+    _reference_identifier: ($) => alias($.identifier, $.reference_identifier),
```
Comment (eladb) [inline libs/tree-sitter-wing/grammar.js:62]: Why the distinction between the three types of identifiers? Seems like they are all the same...

File: libs/wingc/src/lsp/completions.rs [hunk 8]
```diff
@@ -279,7 +281,7 @@ fn get_completions_from_class(
 		.get_env()
 		.iter(true)
 		.filter_map(|symbol_data| {
-			if symbol_data.0 == "init" {
+			if symbol_data.0 == CLASS_INIT_NAME || symbol_data.0 == CLASS_INFLIGHT_INIT_NAME {
```
Comment (eladb) [inline libs/wingc/src/lsp/completions.rs:284]: curious: why the special case for `init` methods?

File: libs/wingc/src/lsp/completions.rs [hunk 9]
```diff
@@ -388,16 +393,16 @@ pub struct ScopeVisitor<'a> {
 	pub found_stmt_index: Option<usize>,
 	/// The scope that contains the target location
 	pub found_scope: Option<&'a Scope>,
-	/// The nearest reference before (or containing) to the target location
-	pub nearest_reference: Option<(&'a Expr, &'a Reference)>,
+	/// The nearest expression before (or containing) to the target location
+	pub nearest_expr: Option<&'a Expr>,
```
Comment (eladb) [inline libs/wingc/src/lsp/completions.rs:397]: :pray:

File: libs/wingc/src/lsp/completions.rs [hunk 10]
```diff
@@ -423,25 +428,12 @@ impl<'a> Visit<'a> for ScopeVisitor<'a> {
...
-						self.nearest_reference = Some((node, r));
-					}
-				}
-				Reference::TypeMember { property, .. } => {
-					if property.span < self.location {
-						self.nearest_reference = Some((node, r));
-					}
-				}
-			}
+		if node.span <= self.location {
```
Comment (eladb) [inline libs/wingc/src/lsp/completions.rs:431]: add some comments to explain what this is doing

File: libs/wingc/src/parser.rs [hunk 11]
```diff
@@ -327,10 +327,18 @@ impl<'s> Parser<'s> {
...
-		})
+		let reference = self.build_reference(&statement_node.child_by_field_name("name").unwrap())?;
+		if let ExprKind::Reference(r) = reference.kind {
+			Ok(StmtKind::Assignment {
+				variable: r,
+				value: self.build_expression(&statement_node.child_by_field_name("value").unwrap())?,
+			})
+		} else {
+			self.add_error(
+				"Expected a reference on the left hand side of an assignment",
```
Comment (eladb) [inline libs/wingc/src/parser.rs:338]: I am a bit confused by the use of the term "reference" here. I would expect the lhs of an assignment to just be a symbol/identifier, not a reference (a "reference" in my mind is refering to something that already exists, while this is actually creating a new symbol which references the expression on the rhs).

File: libs/wingc/src/parser.rs [hunk 12]
```diff
@@ -1270,19 +1316,21 @@ impl<'s> Parser<'s> {
 	fn report_unhandled_errors(&self, root: &Node) {
 		let iter = traverse(root.walk(), Order::Pre);
 		for node in iter {
-			if !self.error_nodes.borrow().contains(&node.id()) {
+			if node.kind() == "AUTOMATIC_SEMICOLON" {
+				_ = self.add_error::<()>("Expected ';'", &node);
```
Comment (eladb) [inline libs/wingc/src/parser.rs:1320]: Nice!

**Review by eladb — APPROVED** [review]
So much goodness in one PR!

Nothing is blocking.

File: libs/wingc/src/parser.rs (hunk 11 above)
Comment (MarkMcCulloh) [reply libs/wingc/src/parser.rs:338]: Note that this function is for assignment and not a declaration. Declarations have only an identifier, but here it is a reference:

```
x = 2;
a.b = 2;
a[0] = 2;
```

File: libs/wingc/src/lsp/completions.rs (hunk 8 above)
Comment (MarkMcCulloh) [reply libs/wingc/src/lsp/completions.rs:284]: You can't really call the constructor (`super` will be a different case) so there's no reason for it to be in the completion list.

File: libs/tree-sitter-wing/grammar.js (hunk 6 above)
Comment (MarkMcCulloh) [reply libs/tree-sitter-wing/grammar.js:44]: _ makes it hidden, which is nice because our AST really doesn't need to show semicolons.
Luckily though, when the external scanner "inserts" a semicolon the `AUTOMATIC_SEMICOLON` node _does_ show up in the AST. So it's kinda a win-win

File: libs/tree-sitter-wing/grammar.js (hunk 7 above)
Comment (MarkMcCulloh) [reply libs/tree-sitter-wing/grammar.js:62]: Initially, I added this because it's handy for debugging grammar conflicts. It makes it clear what rules are used in the grammar because these identifiers are used in specific places. I didn't have to trace the rules like we did on that call.
An additional small benefit is that it makes the grammar much more expressive for the purpose of queries. With that, I could make the tree-sitter highlight query better distinguish between a variable and a property.

afaik it's doesn't hurt to have these, so I figured I would leave it in as a net-positive

File: libs/tree-sitter-wing/package.json [hunk 13]
```diff
@@ -20,7 +20,14 @@
   },
   "scripts": {
     "test": "npx tree-sitter-cli test",
-    "test:update": "npx tree-sitter-cli test --update"
+    "test:update": "npx tree-sitter-cli test --update",
```
Comment (Chriscbr) [inline libs/tree-sitter-wing/package.json:23]: I should have known there was an --update flag... the last time I updated the grammar I was updating the snapshots by hand 😅

File: tools/hangar/__snapshots__/invalid.ts.snap [hunk 14]
```diff
@@ -556,36 +563,25 @@ exports[`json_static.w > stderr 1`] = `
...
-error: Unexpected 'identifier'.
-   --> ../../../examples/tests/invalid/missing_semicolon.w:11:1
-   |
-11 | q2.add_consumer(inflight (m:str): str => {
-   | ^^ Unexpected 'identifier'.
+"error: Expected ';'
+  --> ../../../examples/tests/invalid/missing_semicolon.w:9:3
+  |
+9 | })
+  |   ^ Expected ';'
```
Comment (Chriscbr) [inline tools/hangar/__snapshots__/invalid.ts.snap:570]: Great improvement (also like removing the periods 👍 )
