### PR TITLE
fix(sdk): customized rootId for sim

### LINKED ISSUE #6598: --rootId option does nothing in `sim`
### I tried this:

```wing
log(nodeof(this).app.node.id);
```

Then run `wing compile --rootId hello`

### This happened:

Outputs "root"

### I expected this:

Outputs "hello"

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by tsuf239**
fixes #6598
checked the console too and it doesn't seem to break, the `rootid.test.w` file and its tests work.
## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: apps/wing/src/commands/compile.ts [hunk 1]
```diff
@@ -30,7 +30,7 @@ export interface CompileOptions {
    *
    * @default "Default"
    */
-  readonly rootId?: string;
```
Comment (eladb) [inline apps/wing/src/commands/compile.ts:33]: Why?

File: apps/wing/src/commands/test/test.ts [hunk 2]
```diff
@@ -195,12 +195,12 @@ async function testOne(
 
   let results: std.TestResult[] = [];
   if (shouldExecute) {
+    options.rootId = options.rootId ?? `Test.${nanoid(10)}`;
```
Comment (eladb) [inline apps/wing/src/commands/test/test.ts:198]: Not sure I understand why this change is needed?

It's better to put the id in a local variable and reuse than to mutate the options object

File: apps/wing/src/commands/test/test.ts [hunk 3]
```diff
@@ -195,12 +195,12 @@ async function testOne(
...
     const synthDir = await withSpinner(
       `Compiling ${renderTestName(entrypoint)} to ${target}...`,
       async () =>
         compile(entrypoint, {
           ...options,
-          rootId: options.rootId ?? `Test.${nanoid(10)}`,
```
Comment (eladb) [inline apps/wing/src/commands/test/test.ts:203]: This will cause the id to be non deterministic

**Review by eladb — CHANGES_REQUESTED** [review]

File: apps/wing/src/commands/test/test.ts [hunk 4]
```diff
@@ -192,20 +192,20 @@ async function testOne(
   // determine snapshot behavior
   const snapshotMode = determineSnapshotMode(target, options);
   const shouldExecute = snapshotMode === SnapshotMode.NEVER || snapshotMode === SnapshotMode.DEPLOY;
+  const testOptions = { ...options, rootId: options.rootId ?? `Test.${nanoid(10)}` };
```
Comment (Chriscbr) [inline apps/wing/src/commands/test/test.ts:195]: @eladb @tsuf239 When should random test IDs be used?

my understanding so far:
- if a random ID was used every time someone ran `wing test`, then [snapshot tests](https://www.winglang.io/contributing/rfcs/2024-03-24-snapshot-tests) would be broken since they would produce different snapshots each time
- for cloud testing (currently only in our monorepo, but maybe users will want this done for them in the future), if we don't randomize the ID when running `wing test`, then it's more likely for tests to fail due to spurious resource name conflicts

Comment (tsuf239) [reply apps/wing/src/commands/test/test.ts:195]: it's already in use in the cloud targets (I believe it updates the snapshots each time, from my experience- since the snapshots were invented since the randomization was there before), 
this PR is for making it behave the same way in the sim 
second point is very true :) we added this randomization to be able to run the tests in parallel

Comment (Chriscbr) [reply apps/wing/src/commands/test/test.ts:195]: > I believe it updates the snapshots each time
I see, I wonder if it's a latent bug?

File: examples/tests/valid/this.test.w [hunk 5]
```diff
@@ -1,7 +1,12 @@
+/*\
+args:
+  - --rootId
+  - root
+\*/
```
Comment (Chriscbr) [inline examples/tests/valid/this.test.w:5]: Why is this needed? is the default ID not "root" anymore? I'm not sure I understand how randomizing the ID is needed to fix https://github.com/winglang/wing/issues/6598

Comment (tsuf239) [reply examples/tests/valid/this.test.w:5]: You are right about the randomization, this was reverted, but the args here are needed for the tf-aws compilation hangar test- the default one there is `Default` and not `root`

File: apps/wing/src/commands/test/test.ts (hunk 4 above)
Comment (tsuf239) [reply apps/wing/src/commands/test/test.ts]: yes, as far as I know the snapshots are not even committed: https://github.com/winglang/wing/blob/b1d01275367b3eb2476528ec56d7b29d193492b4/examples/tests/sdk_tests/.gitignore#L1

**Review by Chriscbr — APPROVED** [review]

**Review by Chriscbr — APPROVED** [review]
LGTM
