### PR TITLE
fix(compiler): extending unknown classes causes panic

### LINKED ISSUE #2650: Extending unknown classes causes panic
### I tried this:

I tried compiling this Wing file with `wing compile hello.w`:

```js
// hello.w
bring cloud;

class A extends B {}
```

### This happened:

```
thread '<unnamed>' panicked at 'Preflight class A's parent any is not a preflight class', libs/wingc/src/type_check.rs:2213:29
stack backtrace:
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/009c6462:wasm-function[240]:0xde0b0)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/009c6462:wasm-function[1460]:0x186952)
    at wingc::type_check::TypeChecker::type_check_scope::h78016c045164aa11 (wasm://wasm/009c6462:wasm-function[427]:0x121907)
    at wingc::type_check::hc3b72124dd314895 (wasm://wasm/009c6462:wasm-function[115]:0xa88ba)
    at wingc_compile (wasm://wasm/009c6462:wasm-function[276]:0xeb66c)
    at wingc_compile.command_export (wasm://wasm/009c6462:wasm-function[1606]:0x18bea3)
    at Object.invoke (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/wingc.js:145:37)
    at compile (/Users/chrisr/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/compile.js:125:38)
```

### I expected this:

It should show a compiler diagnostic saying that "B" is an unknown symbol / has not been defined anywhere

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

0.17.25

### Wing Console Version

_No response_

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #2650

Misc:
- Merged one test file (invalid/construct.w) into a related one (invalid/structs.w)
- Refactored some internal methods `expr_error` and `stmt_error` so they can accept both &str and String for convenience

----
- [x] PR title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] PR description explains motivation and solution
- [x] Tests added
- [x] Docs updated
- [ ] Needs end-to-end tests (`pr/e2e-full` label)

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: tools/hangar/__snapshots__/invalid.ts.snap [hunk 1]
```diff
@@ -234,12 +248,6 @@ error: Expected type to be \\"IQueueAddConsumerHandler (inflight (str): void)\\"
 "
 `;
 
-exports[`construction.w > stderr 1`] = `
-"error: Cannot instantiate type \\"BucketProps\\" because it is not a class
-
-"
-`;
```
Comment (Chriscbr) [inline tools/hangar/__snapshots__/invalid.ts.snap:241]: This test was moved to another file

File: tools/hangar/__snapshots__/invalid.ts.snap [hunk 2]
```diff
@@ -1069,9 +1077,6 @@ error: Expected 'b' to be a type but it's a variable
   |                          ^ Expected 'b' to be a type but it's a variable
 
 
-error: Inflight class c's parent \\"any\\" is not a class
```
Comment (Chriscbr) [inline tools/hangar/__snapshots__/invalid.ts.snap:1072]: This error and the one below are are removed since we already give an error in the same place ("Expected 'b' to be a type but it's a variable")

**Review by MarkMcCulloh — APPROVED** [review]

**Review by hasanaburayyan — APPROVED** [review]
