### PR TITLE
fix(cli): `wing pack` does not enforce using `peerDependencies`

### LINKED ISSUE #5470: `wing pack` should enforce `peerDependencies` usage instead of regular dependencies
### Use Case

When wing libraries are compiled, the generated javascript is executed in the consumer's context. Because of that, transitive dependencies are suddenly expected to be actual dependencies of the consumer for the purpose of module resolution.

using `peerDependencies` more correctly models this relationship and should fix usage with pnpm and package managers that correctly enforce dependency closures.

### Proposed Solution

`wing pack` should error if `dependencies` is used in the package.json and instead suggest using `peerDependencies`

### Further clarification

If `A` depends on `B`, when you install `A` with npm your node_modules look like this:

```
node_modules
  A
  B
preflight.js
```

This means that preflight.js can import `B` even though it's not a direct dependency.

pnpm instead does something like this: (there are other misdirections involved but this is the gist)

```
node_modules
  A
    node_modules
      B
preflight.js
```

The js we emit makes direct references to `B` because it originally came from wing files in `A`, so they no longer resolve correctly, both at runtime and also during compilation because our resolver code isn't smart enough.

If you use peer dependencies, `pnpm install` will go back to creating a sufficiently flat node_modules with both A and B.

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

### PR DESCRIPTION
**Pull request by garysassano**
Closes #5470

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: apps/wing/src/commands/pack.ts [hunk 1]
```diff
@@ -120,6 +120,13 @@ export async function pack(options: PackageOptions = {}): Promise<string> {
       }
     }
 
+    // check package.json has `dependencies`
+    if (pkgJson.dependencies) {
```
Comment (MarkMcCulloh) [inline apps/wing/src/commands/pack.ts:124]: Add a check to make sure there are values in this key (an empty dep map is weird but fine)

File: apps/wing/src/commands/pack.ts [hunk 2]
```diff
@@ -120,6 +120,13 @@ export async function pack(options: PackageOptions = {}): Promise<string> {
...
+      throw new Error(
+        `Wing libraries should use "peerDependencies" instead of "dependencies" in package.json.`
+      );
```
Comment (MarkMcCulloh) [inline apps/wing/src/commands/pack.ts:127]: We often write error messages as "problem, solution". So maybe

```suggestion
      throw new Error(
        `Cannot create package with "dependencies" in package.json. Use "peerDependencies" instead.`
      );
```

**Review by MarkMcCulloh — APPROVED** [review]
