### PR TITLE
feat(cli): ask politely for bug reports when panic occurs

### LINKED ISSUE #912: CLI: ask users to report an issue whenever compiler panics
### Summary

_No response_

### Feature Spec

If the user runs `wing compile` and the compiler panics (there is an unexpected error in our Rust code), we would like the CLI to print out a message like "An unexpected error occurred while Wing was compiling! Can you please create an issue on GitHub (https://github.com/winglang/wing/issues/new/choose) with the code you were compiling?"

### Use Cases

Help distinguish between regular compilation errors and bugs in our compiler

### Implementation Notes

Maybe it could be added with https://doc.rust-lang.org/nomicon/panic-handler.html.
Or, it could maybe be implemented in the [CLI code](https://github.com/winglang/wing/blob/main/apps/wing/src/commands/compile.ts) (where it's invoking the compiler as a wasm module)

### Component

Compiler

### PR DESCRIPTION
**Pull request by Chriscbr**
Closes #912

Panic error messages should look something like this now
Screenshot 2023-02-23 at 12 07 30 PM

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: apps/wing/src/commands/compile.ts [hunk 1]
```diff
@@ -90,8 +94,19 @@ export async function compile(entrypoint: string, options: ICompileOptions) {
...
   const arg = `${normalPath(wingFile)};${normalPath(workDir)}`;
   log(`invoking %s with: "%s"`, WINGC_COMPILE, arg);
-  const compileResult = wingCompiler.invoke(wingc, WINGC_COMPILE, arg);
+  let compileResult;
+  try {
+    compileResult = wingCompiler.invoke(wingc, WINGC_COMPILE, arg);
+  } catch (e) {
+    // This is a bug in Wing, not the user's code.
+    console.error(e);
+    console.log("  " + chalk.bold.red("error:") + " An internal error occurred while Wing was compiling. Please report this bug by creating an issue on GitHub (github.com/winglang/wing) with your Wing code.");
```
Comment (eladb) [inline apps/wing/src/commands/compile.ts:103]:
```suggestion
    console.log("\n\n" + chalk.bold.red("Internal error:") + " An internal compiler error occurred. Please report this bug by creating an issue on GitHub (github.com/winglang/wing/issues) with your code and this trace.");
```

**Review by staycoolcall911 — APPROVED** [review]

File: apps/wing/src/commands/compile.ts (hunk 1 above)
Comment (Chriscbr) [reply apps/wing/src/commands/compile.ts:103]: We should write a style guide for errors at some point

(related: https://developers.google.com/tech-writing/error-messages)
