### PR TITLE
fix(sdk): fix `fs.readYaml()` throwing node warnings

### LINKED ISSUE #4540: `fs.readYaml()` with certain content can cause node warning
### I tried this:

See existing yaml test case https://github.com/winglang/wing/blob/94e39536d5f1f94cd33230bea3added3072da1c4/examples/tests/sdk_tests/fs/yaml.main.w#L11-L16

### This happened:

stderr:

```shell
(node:92057) Warning: Keys with collection values will be stringified due to JS Object restrictions: "{ content }". Set mapAsMap: true to use object keys.
(Use `node --trace-warnings ...` to show where the warning was created)
```

### I expected this:

No warning, or an errror, or at least a wingified warning of some kind? Feels weird to be exposed to nodejs warnings.

### Is there a workaround?

_No response_

### Component

SDK

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by garysassano**
Closes #4540

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Review by MarkMcCulloh — COMMENTED** [review]
Add a test to confirm the warning is gone and it still behaves as expected?

**Comment by garysassano** [comment]
@MarkMcCulloh I restored the test that was previously throwing the warning.

File: libs/wingsdk/src/fs/fs.ts [hunk 1]
```diff
@@ -221,8 +221,15 @@ export class Util {
...
   public static readYaml(filepath: string): Json[] {
     const text = Util.readFile(filepath);
-    const yamlObjs = yaml.parseAllDocuments(text);
-    return yamlObjs.map((o: any) => JSON.parse(JSON.stringify(o)) as Json);
+    const yamlDocs = yaml.parseAllDocuments(text);
+    return yamlDocs.map((doc) => {
+      if (doc.contents && doc.contents.toJSON) {
+        return doc.contents.toJSON();
+      } else {
+        console.warn("Unexpected document structure:", doc);
```
Comment (eladb) [inline libs/wingsdk/src/fs/fs.ts:229]: Why not throw?

**Review by eladb — CHANGES_REQUESTED** [review]

File: libs/wingsdk/src/fs/fs.ts (hunk 1 above)
Comment (garysassano) [reply libs/wingsdk/src/fs/fs.ts:229]: I assumed you'd prefer to continue processing the remaining documents in the file instead of stopping the process altogether.

File: examples/tests/sdk_tests/fs/yaml.test.w [hunk 2]
```diff
@@ -8,6 +8,13 @@ let data = Json {
     "arr": [1, 2, 3, "test", { "foo": "bar" }]
 };
 
+try {
+    fs.writeFile(filepath, "invalid: {{ content }}, invalid");
```
Comment (eladb) [inline examples/tests/sdk_tests/fs/yaml.test.w:12]: Move this outside of the `try`

**Review by eladb — APPROVED** [review]
