### PR TITLE
fix: unable to load jsii modules in vscode, missing highlights, and verbose diagnostics for certain types

### LINKED ISSUE #1488: Cannot import jsii modules from outside of the Wing project directory
#1397 implements basic support for importing jsii libraries in Wing. jsii libraries are found using the node module resolution algorithm (so all you need to do is `npm install <library>` to use the library in your Wing project).

However, since we are invoking the compiler with WebAssembly, we must explicitly declare what paths in the file system to give it access to - today, we only give it access to the parent directory of your Wing source file. This means npm modules in parent `node_modules` directories will not be found, even importing them in the JavaScript would work.

To implement this, we would need to either grant access to the user's entire file system, or add some kind of dynamic checking of  for `brought` file system paths, or handle some of the importing logic outside of the WebAssembly runtime.

Examples:

```
bring "my-lib" as my_lib1; // where "my-lib" is in a parent or grandparent node_modules folder
bring "/path/outside/of/wing/project" as my_lib2;
```

Do you have any use cases where you would like to import a library from outside of your Wing project directory? If so, please tell us and give this issue a +1 (👍) to help us prioritize this feature.

### LINKED ISSUE #1530: `bring` jsii library causes VS Code extension to crash
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```
bring "jsii-code-samples" as jsii;
```

### I expected this:

It works

### Instead, this happened:

Wing Language Server crashed

### Component:

IDE Extension

### Wing Version:

0.5.34

### Node.js Version:

18.12.1

### Platform(s):

MacOS

### Anything else?

_No response_

### LINKED ISSUE #1549: fn is highlighted like builtin keyword
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

I wrote this in a Wing file in VS Code
```
bring cloud;

let fn = new cloud.Function(inflight () => {
  print("hi");
});
let fn2 = new cloud.Function(inflight () => {
  print("hi");
});
```

### I expected this:

VS Code extension highlights `fn` and `fn2` with the same color

### Instead, this happened:

`fn` is highlighted in the same color as `inflight` and `let` and `bring`

### Component:

IDE Extension

### Wing Version:

0.5.36

### Node.js Version:

18.12.1

### Platform(s):

MacOS

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Kinda a mishmash, was working on the language server this came out of it

Fixes #1549
Fixes #1530
Fixes #1488

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: apps/wing/src/wingc.ts [hunk 1]
```diff
@@ -25,12 +25,14 @@ export interface WingCompilerLoadOptions {
 
 export async function load(options: WingCompilerLoadOptions) {
   const preopens = {
+    "/": "/",
```
Comment (MarkMcCulloh) [inline apps/wing/src/wingc.ts:28]: idk if this is controversial, but we are not using WASM for it's security sandboxing right now. Anything limiting of filesystem access has to be handled in the runtime invoking wasm.

File: apps/wing/src/wingc.ts [hunk 2]
```diff
@@ -25,12 +25,14 @@ export interface WingCompilerLoadOptions {
...
     // .jsii access
     [WINGSDK_MANIFEST_ROOT]: WINGSDK_MANIFEST_ROOT,
     ...(options.preopens ?? {}),
   } as Record<string, string>;
 
   if (process.platform === "win32") {
+    preopens["C:\\"] = "C:\\";
```
Comment (MarkMcCulloh) [inline apps/wing/src/wingc.ts:35]: tbh it may be impossible to grant "full access" to windows, until we delegate fs access to node we will have issues here

File: apps/wing/src/wingc.ts [hunk 3]
```diff
@@ -25,12 +25,14 @@ export interface WingCompilerLoadOptions {
 
 export async function load(options: WingCompilerLoadOptions) {
   const preopens = {
+    "/": "/",
     // .jsii access
     [WINGSDK_MANIFEST_ROOT]: WINGSDK_MANIFEST_ROOT,
```
Comment (MarkMcCulloh) [inline apps/wing/src/wingc.ts:30]: Even though we add "/", adding other explicit preopens is useful in the case of Windows and if any files we need are in drives other than C.

File: apps/wing/src/wingc.ts (hunk 1 above)
Comment (eladb) [reply apps/wing/src/wingc.ts:28]: Why is this needed?

File: apps/wing/src/wingc.ts (hunk 2 above)
Comment (eladb) [reply apps/wing/src/wingc.ts:35]: Do we have an issue about this?

File: examples/tests/valid/bring_jsii_path.w [hunk 4]
```diff
@@ -0,0 +1,9 @@
+bring cloud;
+bring "./node_modules/jsii-code-samples" as jsii_code_samples;
```
Comment (eladb) [inline examples/tests/valid/bring_jsii_path.w:2]: Why do we need `./node_modules` here? Shouldn't this behave like `require`?

File: libs/wingii/src/node_resolve.rs [hunk 5]
```diff
@@ -67,8 +67,8 @@ pub fn resolve_from(target: &str, basedir: &Path) -> Result<PathBuf, Box<dyn Err
 		basedir
 	};
 
-	// 3. If X begins with './' or '/' or '../'
-	if target.starts_with("./") || target.starts_with('/') || target.starts_with("../") {
+	// 3. If X begins with './' or '../' or '/'
+	if target.starts_with("./") || target.starts_with("../") || target.starts_with("/") {
```
Comment (eladb) [inline libs/wingii/src/node_resolve.rs:71]: Extract to a utility function with some docs an reuse

File: examples/tests/valid/bring_jsii_path.w (hunk 4 above)
Comment (MarkMcCulloh) [reply examples/tests/valid/bring_jsii_path.w:2]: We don't need it, but this file is testing the behavior of importing from a path rather than a node module (https://github.com/winglang/wing/issues/1488)

File: apps/wing/src/wingc.ts (hunk 1 above)
Comment (MarkMcCulloh) [reply apps/wing/src/wingc.ts:28]: preopens grant the WASI runtime access to the host filesystem, and without some fancy analysis we don't know if the user will attempt to import libraries from anywhere on the system. 
This is also very useful for the lsp, which can open a file anywhere on the user's system at a moment's notice.

File: apps/wing/src/wingc.ts (hunk 2 above)
Comment (MarkMcCulloh) [reply apps/wing/src/wingc.ts:35]: https://github.com/winglang/wing/issues/1560

File: examples/tests/valid/bring_jsii_path.w (hunk 4 above)
Comment (MarkMcCulloh) [reply examples/tests/valid/bring_jsii_path.w:2]: there is already another test that does `bring "jsii-code-samples"`

**Review by eladb — APPROVED** [review]

File: apps/wing/src/wingc.ts (hunk 1 above)
Comment (Chriscbr) [reply apps/wing/src/wingc.ts:28]: Yeah I wasn't sure whether to add this to my bring jsii PR or not (security concerns and all) but I think it makes sense in the end. We could always add some kind of "secure" compile API/option later if needed
