### PR TITLE
fix(compiler): reserved words are not blocked

### LINKED ISSUE #3110: Javascript reserved words (such as null) should be reserved words in Wing as well
### I tried this:

```
// main.w
bring cloud;
bring "cdktf" as cdktf;
bring "@cdktf/provider-null" as null;
```

```
wing compile main.w
```

similar for 

```
// main.w
bring cloud;
bring "cdktf" as cdktf;
bring "@cdktf/provider-null" as nullish;

let null = new nullish.provider.NullProvider();
```

### This happened:

```
 wing compile main.w
Error: ERROR: Unexpected token 'null'

target/main.wsim.016318.tmp/.wing/preflight.js:7
   const cloud = require('@winglang/sdk').cloud;
   const cdktf = require("cdktf");
>> const null = require("@cdktf/provider-null");
   class $Root extends $stdlib.std.Resource {
     constructor(scope, id) {

    at compile (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/compile.js:117:19)
```

### I expected this:

- No error or
- Immediate feedback from the compiler / language server that this is not working

### Is there a workaround?

Don't use `null` as a variable

### Component

Compiler

### Wing Version

_No response_

### Wing Console Version

0.22.24

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #3110

This is list is pretty naive, I think we should eventually do some mangling/cleanup of the JS we emit to avoid so many reserved values. Since I believe there's more work to do, I didn't touch the spec yet (See https://github.com/winglang/wing/issues/1964).

This change will at least prevent strange runtime errors due to using reserved words. Added a special case for "constructor" as a method name, since it's not technically reserved elsewhere.

Misc:
- Changed the add_error in the parser to have a version that doesn't return anything. Sorry that this caused a bit of a noisy diff but I was so tired of that dumb `let _ = ...` thing

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributing/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/parser.rs [hunk 1]
```diff
@@ -41,6 +41,99 @@ static UNIMPLEMENTED_GRAMMARS: phf::Map<&'static str, &'static str> = phf_map! {
...
+	"Object",
+	"Set",
+
+	// consts declared by the compiler in preflight
+	"$stdlib",
+	"$outdir",
+	"$wing_is_test",
+	"$App",
+	"$AppBase",
+	"$Root",
```
Comment (Chriscbr) [inline libs/wingc/src/parser.rs:134]: I might just skip these since the list might get out of date more quickly (and if a user gets errors by declaring a variable like "$stdlib", it would probably be better to just track that as a compiler bug instead IMO, since there's no technical reason they have to be reserved). Up to you though

File: libs/wingc/src/parser.rs [hunk 2]
```diff
@@ -41,6 +41,99 @@ static UNIMPLEMENTED_GRAMMARS: phf::Map<&'static str, &'static str> = phf_map! {
...
+	"try",
+	"typeof",
+	"var",
+	"void",
+	"volatile",
+	"while",
+	"with",
+	"yield",
+
+	// wing-specific reserved words
```
Comment (Chriscbr) [inline libs/wingc/src/parser.rs:111]: Do we also need to reserve words like `str`, `num`, etc.? I don't know but figured I'd ask

**Review by Chriscbr — APPROVED** [review]

File: libs/wingc/src/parser.rs (hunk 2 above)
Comment (MarkMcCulloh) [reply libs/wingc/src/parser.rs:111]: Ah good catch. I initially left them out because I didn't think so but thinking again yeah they should be reserved.

File: libs/wingc/src/parser.rs (hunk 1 above)
Comment (MarkMcCulloh) [reply libs/wingc/src/parser.rs:134]: Makes sense, I guess I'll take them out since there's no chance for them to show up during inflight (which is where it's a much worse bug)
