### PR TITLE
fix: ensure wing process is killed from vscode

### LINKED ISSUE #4119: VSCode console does does kill wing subprocess after closing console tab
### I tried this:

Open wing file in vscode
Open console for file (click wing icon in top-right)
Close console tab

### This happened:

Visited the same URL in browser and see that the console is still running

### I expected this:

dead console

### Is there a workaround?

Manually kill process

### Component

Wing Console, IDE Extension

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #4119

Since wing itself is being run in a child process of vscode, it wasn't handling the kill signal. Detaching it allows it to have its own process tree and be killed more reliably. Special handling is needed for windows, of course.

This also ensures that any process spawned by `wing it` itself is terminated too.

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: apps/wing/src/commands/run.ts [hunk 1]
```diff
@@ -49,19 +49,27 @@ export async function run(entrypoint?: string, options?: RunOptions) {
...
     wingfile: entrypoint,
     requestedPort,
     hostUtils: {
-      async openExternal(url) {
+      async openExternal(url: string) {
         await open(url);
       },
     },
-    requireAcceptTerms: true,
+    requireAcceptTerms: !!process.stdin.isTTY,
```
Comment (Chriscbr) [inline apps/wing/src/commands/run.ts:60]: Is this for unit testing? or just an unrelated bug we had?

**Review by Chriscbr — APPROVED** [review]

File: apps/wing/src/commands/run.ts (hunk 1 above)
Comment (MarkMcCulloh) [reply apps/wing/src/commands/run.ts:60]: No related bug for it afaik, and it's not for testing. I made the change in search of root cause, and left it in cause it seemed like a better thing to do.
