### PR TITLE
fix(compiler): bundling error when using computed struct value inflight

### LINKED ISSUE #5458: bundling error when using computed struct value
### I tried this:

```wing
struct s {
  a: str;
}

test "" {
  let x: s = s{
    a: () => {
      return "b";
    }()
  };
}
```

### This happened:

```
fail ┌ main.wsim » root/env0/test:
     │ runtime error: Failed to bundle function: Error: Build failed with 1 error:
     │ inflight.$Closure1-1.js:11:39: ERROR: Unexpected "=>"
     │    --> ../../../Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/bundling.ts:63:11
     │    | 
     │    | if (esbuild.errors.length > 0) {
     │    |   const errors = esbuild.errors.map((e) => e.text).join("\n");
     │ 63 |   throw new Error(`Failed to bundle function: ${errors}`);
     │    |         ^
     │ at  (inflight.$Closure1-1.js:11:39)
     │ at createBundle (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/bundling.ts:63:11)
     │ at loadBundleOnce (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/sandbox.ts:102:33)
     │ at call (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/shared/sandbox.ts:121:5)
     │ at withTrace (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/simulator/simulator.ts:673:24)
     └ at runTest (/Users/eladcohen/.nvm/versions/node/v18.14.2/lib/node_modules/winglang/node_modules/@winglang/sdk/src/target-sim/test-runner.inflight.ts:47:7)
```

### I expected this:

_No response_

### Is there a workaround?

Add a variable for the closure:
```ts
struct s {
  a: str;
}

test "" {
  let f = () => {
    return "b";
  };
  let x: s = s{
    a: f()
  };
}
```

### Anything else?

_No response_

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #5458

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingc/src/jsify.rs [hunk 1]
```diff
@@ -1286,6 +1286,7 @@ impl<'a> JSifier<'a> {
 		&self,
 		class: Option<&AstClass>,
 		func_def: &FunctionDefinition,
+		is_closure: bool,
```
Comment (MarkMcCulloh) [inline libs/wingc/src/jsify.rs:1289]: nit: should a jsify test be added as well?

**Review by MarkMcCulloh — APPROVED** [review]

File: libs/wingc/src/jsify.rs (hunk 1 above)
Comment (Chriscbr) [reply libs/wingc/src/jsify.rs:1289]: How do you mean?

Comment (MarkMcCulloh) [reply libs/wingc/src/jsify.rs:1289]: Adding a case for this fix in the jsify snapshot tests, the ones in `wingc/jsify/tests.rs`

**Review by hasanaburayyan — APPROVED** [review]
