### PR TITLE
fix(compiler): array access operator precedence

### LINKED ISSUE #6276: Array index precedence bug
### I tried this:

```js
let arr = [5, 5];

assert(arr[0] == arr[1]);
```

### This happened:

Compiling raised two errors

```
error: Expected type to be "num", but got "Array<num>" instead
  --> main.w:3:8
  |
3 | assert(arr[0] == arr[1]);
  |        ^^^^^^^^^^^^^ Expected type to be "num", but got "Array<num>" instead


error: Type "bool" is not indexable
  --> main.w:3:8
  |
3 | assert(arr[0] == arr[1]);
  |        ^^^^^^^^^^^^^ Type "bool" is not indexable
```

### I expected this:

No error

### Is there a workaround?

Wrap the array access with extra parentheses:

```js
assert(arr[0] == (arr[1]));
```

### Anything else?

_No response_

### Wing Version

0.71.0

### Node.js Version

20.12.2

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #6276 by adding a precedence level for array access expressions. I inserted the precedence right below member access expressions, similar to JavaScript's operator precedence [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Operator_precedence#table).

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/tree-sitter-wing/grammar.js [hunk 1]
```diff
@@ -13,9 +13,10 @@ const PREC = {
   UNARY: 120,
   OPTIONAL_TEST: 130,
   POWER: 140,
-  MEMBER: 150,
-  CALL: 160,
-  OPTIONAL_UNWRAP: 170,
+  SUBSCRIPT: 150, // x[0]
```
Comment (MarkMcCulloh) [inline libs/tree-sitter-wing/grammar.js:16]: subscript? This could match the rule instead with something like STRUCTURED_ACCESS

File: examples/tests/valid/indexing.test.w
Comment (MarkMcCulloh) [inline examples/tests/valid/indexing.test.w:1]: Could you add a tree-sitter test case as well? Could be faster to spot regressions at that level

**Review by MarkMcCulloh — APPROVED** [review]
