### PR TITLE
fix(compiler): blocks can't start on a newline

### LINKED ISSUE #3985: Expected block | Unknown parser error
### I tried this:

**Issue :** Placement of the curly braces after if statement may throw an error on compilation 
I was writing a simple program 
```
bring util; 
let var c  = true; 
if(c == true)
{
 log("Yes" );
}
```

### This happened:

**I got this error** 
C:\Desktop\Winglang>wing compile Hello.w 
error: Expected block
  --> Hello.w:3:14
  |
3 | if(c == true)
  |              ^ Expected block

error: Unknown parser error
  --> Hello.w:5:13
  |
5 |  log("Yes" );
  |             ^ Unknown parser error

error: Expected ';'
  --> Hello.w:6:2
  |
6 | }
  |  ^ Expected ';'

### I expected this:

When i run it like this 
```
bring util; 
let matches = util.regMatch("p([a-z]+)ch" , "peach")
if(matches == true){
  log("Peaches was matched to our regex");
}
else{
log("No match found");
}
```
It works perfectly 

```

if ( condition) {
// Works
}

vs 

if( )
{
// Doesnot Work
}
```

### Is there a workaround?

_No response_

### Component

Language Design, Compiler, SDK

### Wing Version

0.25.28

### Node.js Version

18.16.0

### Platform(s)

Windows

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #3985

For the record, I do not officially endorse

```
if stuff
{

}
```

but I guess it should be allowed to parse correctly :)

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/tree-sitter-wing/src/scanner.c [hunk 1]
```diff
@@ -169,8 +169,6 @@ static bool scan_automatic_block(TSLexer *lexer)
       return false;
     if (lexer->is_at_included_range_start(lexer))
       return true;
-    if (lexer->lookahead == '\n')
-      break;
```
Comment (MarkMcCulloh) [inline libs/tree-sitter-wing/src/scanner.c:173]: This was copied from the automatic semicolon insertion, but it's not a helpful heuristic here.

**Review by yoav-steinberg — APPROVED** [review]
:clap:
