### PR TITLE
fix(compiler): assert doesn't work with string interpolation

### LINKED ISSUE #1833: assert doesn't work with string interpolation
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```ts (wing) 
let s = "hello";
if "${s}" == "${s}" {  } // compiles and works
assert("" == ""); //compiles and works
assert(s == s); //compiles and works
assert("${s}" == "${s}"); // doens't compile due to backticks I assume
```

```sh
wing compile -t  sim  a.w
```

### I expected this:

to compile and work 

### Instead, this happened:

```sh
wingly % wing compile -t  sim  story13.w
preflight error: missing ) after argument list

  note: intermediate javascript code (/private/tmp/wingly/target/.wing/preflight.js):
     {((cond) => {if (!cond) throw new Error(`assertion failed: '("" === "")'`)})(("" === ""))};
     {((cond) => {if (!cond) throw new Error(`assertion failed: '(s === s)'`)})((s === s))};
>>   {((cond) => {if (!cond) throw new Error(`assertion failed: '(`${s}` === `${s}`)'`)})((`${s}` === `${s}`))};
   }
   }
  note: run with `NODE_STACKTRACE=1` environment variable to display a stack trace
```

### Component:

Compiler

### Wing Version:

0.5.134

### Node.js Version:

_No response_

### Platform(s):

_No response_

### Anything else?

It is probably related to the backticks in assert implementation. 

Maybe we should lint backticks out from our implementation or solve this issue from the ground up

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #1833

The high level idea behind this fix is to avoid using backtick-strings in our generated JavaScript. These lead to a lot of issues that can be avoided by using other concatenation strategies that do not introduce grammar complexities. In this case, I decided to use `String.raw()`, but translating interpolated strings into a sequence of `+` operations probably could have worked too.

The other major change I did was improving the errors emitted by `assert()` so that it shows the original Wing source code that you asserted, not the emitted JavaScript. For example, now an error looks like:

```
assertion failed: b.list().length == 1
```
     instead of:  
```
assertion failed: '((await b.list()).length === 1)'
```

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/jsify.rs [hunk 1]
```diff
@@ -1961,3 +1984,51 @@ fn jsify_type_name(t: &Vec<Symbol>, phase: Phase) -> String {
 		p.join(".")
 	}
 }
+
+fn lookup_span(span: &WingSpan, source_path: &Path) -> String {
+	let source = std::fs::read_to_string(source_path)
```
Comment (eladb) [inline libs/wingc/src/jsify.rs:1989]: Does it make sense to read this from a file every time we are doing a lookup? Maybe we can just store the source somewhere and propagate down?

How about creating something like `CompilerContext` object that maintains all the sources as well as e.g. `Types`?

(I am less concerned about performance and more about the fact that very soon we will have multiple sources and then it makes sense to manage them in a centralized facility).

File: libs/wingc/src/jsify.rs [hunk 2]
```diff
@@ -1961,3 +1984,51 @@ fn jsify_type_name(t: &Vec<Symbol>, phase: Phase) -> String {
...
+			result.push('\n');
+		}
+
+		result.push_str(&lines[end_line][..end_col]);
+	}
+
+	result
+}
+
+fn escape_javascript_string(s: &str) -> String {
```
Comment (eladb) [inline libs/wingc/src/jsify.rs:2018]: maybe a couple of a small unit tests for these helper functions?

File: libs/wingc/src/jsify.rs [hunk 3]
```diff
@@ -1961,3 +1984,51 @@ fn jsify_type_name(t: &Vec<Symbol>, phase: Phase) -> String {
...
+	let mut result = String::new();
+
+	for c in s.chars() {
+		match c {
```
Comment (eladb) [inline libs/wingc/src/jsify.rs:2022]: can you reference the source specification that tells us this is an exhaustive list?

**Review by eladb — APPROVED** [review]

File: libs/wingc/src/jsify.rs (hunk 1 above)
Comment (Chriscbr) [reply libs/wingc/src/jsify.rs]: Updated to use the `Files` utility. I like the compiler context object idea though we have another object also already named `CompilationContext` and I'm not sure if I should be touching it because it's part of a thread_local

File: libs/wingc/src/jsify.rs (hunk 2 above)
Comment (Chriscbr) [reply libs/wingc/src/jsify.rs:2018]: Done

File: libs/wingc/src/jsify.rs (hunk 3 above)
Comment (Chriscbr) [reply libs/wingc/src/jsify.rs:2024]: Added a comment
