### PR TITLE
fix(compiler): unable to create array of valid heterogeneous values

### LINKED ISSUE #3883: Cannot create array of heterogeneous values
### I tried this:

```js
class Animal {}
class Cat extends Animal {}
class Dog extends Animal {}

let arr = Array<Animal>[
  new Cat(),
  new Dog(),
];
```

### This happened:

I get a type checking error

```
error: Expected type to be "Cat", but got "Dog" instead
  --> array.w:7:3
  |
7 |   new Dog(),
  |   ^^^^^^^^^ Expected type to be "Cat", but got "Dog" instead
```

### I expected this:

The code should compile

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

0.25.23

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #3883

Removed a function that didn't really do much, added some comments, and generally tweaked the type-checking for literals

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: tools/hangar/__snapshots__/invalid.ts.snap [hunk 1]
```diff
@@ -1572,18 +1565,11 @@ error: Expected type to be \\"num\\", but got \\"str\\" instead
...
    |
 11 | let s2 = MutSet<num>[1, \\"2\\", 3];
-   |          ^^^^^^^^^^^^^^^^^^^^^^ Expected \\"Array\\" type, found \\"MutSet<num>\\"
-
-
-error: Expected type to be \\"num\\", but got \\"str\\" instead
-   --> ../../../examples/tests/invalid/mut_container_types.w:11:25
-   |
-11 | let s2 = MutSet<num>[1, \\"2\\", 3];
-   |                         ^^^ Expected type to be \\"num\\", but got \\"str\\" instead
```
Comment (MarkMcCulloh) [inline tools/hangar/__snapshots__/invalid.ts.snap:1586]: This error no longer happens, and imo I'm not sure if it should be considered a regression. 
`MutSet<num>[1, "2", 3]` is simply not a valid syntax, the fact that it worked before was kinda an accident of the implementation.

We could probably get it working intentionally, but idk how important that is.

Comment (Chriscbr) [reply tools/hangar/__snapshots__/invalid.ts.snap:1586]: Looks fine to me

File: examples/tests/valid/std_containers.w [hunk 2]
```diff
@@ -40,4 +40,13 @@ let immutMap = mutMap.copy();
...
+assert(nestedMap.get("a").get("b").get("c") == "hello");
+
+class Animal {}
+class Cat extends Animal {}
+class Dog extends Animal {}
+
+let heterogeneousArray = Array<Animal>[
+  new Cat(),
+  new Dog(),
+];
```
Comment (Chriscbr) [inline examples/tests/valid/std_containers.w:52]: Can we battle-test this a little bit more? For example, adding `Set<Animal>`, `Map<Animal>`, or `Array<Array<Animal>>` test cases?

**Review by Chriscbr — APPROVED** [review]
