### PR TITLE
fix: panic when handling malformed package.json

### LINKED ISSUE #4070: Compiler bug (panicked at 'called `Option::unwrap()`  on mac os
### I tried this:

log("hello");

### This happened:

Failed to compile.

error: Compiler bug (panicked at 'called `Option::unwrap()` on a `None` value', libs/wingii/src/util.rs:37:17) during parsing, please report at https://www.winglang.io/contributing/start-here/bugs
  |
1 | log("hello");
  |     ^^^^^^^ Compiler bug (panicked at 'called `Option::unwrap()` on a `None` value', libs/wingii/src/util.rs:37:17) during parsing, please report at https://www.winglang.io/contributing/start-here/bugs

### I expected this:

expected to log hello

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

0.29.0

### Node.js Version

18.15.0

### Platform(s)

MacOS

### Anything else?

[Related slack thread](https://winglang.slack.com/archives/C04BBDQUWQP/p1693837449106219)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
Screenshot 2023-09-05 at 12 40 26 am

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
fixes #4070

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingii/src/util.rs [hunk 1]
```diff
@@ -86,3 +74,56 @@ pub mod package_json {
 		}
 	}
 }
+
+#[cfg(test)]
+mod tests {
+	use super::*;
+	use serde_json::json;
+	#[test]
+	fn test_dependencies_of() {
```
Comment (eladb) [inline libs/wingii/src/util.rs:83]: do we want to test some malformed json cases?

Comment (MarkMcCulloh) [reply libs/wingii/src/util.rs:83]: You mean like invalid json text? Sure, but everything in this file already assumed a successfully parsed file (`serde_json::Value`) so going any further out isn't in scope for this pr fix.

**Review by Chriscbr — APPROVED** [review]
