### PR TITLE
fix: cloud.Service cant capture api.url

### LINKED ISSUE #4369: `cloud.Service` can't capture `api.url`
### I tried this:

compiling this code:

```ts
bring cloud;

let api = new cloud.Api();

new cloud.Service(inflight () => {
  log(api.url);
});
```

### This happened:

got this error:

```
eladcohen@Elads-w-MacBook-Pro tmp % wing compile main.w
ERROR: Tokens can only be bound by a Function for now

target/main.wsim.197650.tmp/.wing/preflight.js:37
         _registerBind(host, ops) {
           if (ops.includes("handle")) {
>>           $Closure1._registerBindObject(api.url, host, []);
           }
           super._registerBind(host, ops);
```

### I expected this:

code to compile

### Is there a workaround?

_No response_

### Component

SDK

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by eladcon**
Tokens in simulator can also bind now to a `cloud.Service`

Fixes #4369 

## Checklist

- [X] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [X] Description explains motivation and solution
- [X] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingsdk/src/target-sim/tokens.ts [hunk 1]
```diff
@@ -61,10 +60,6 @@ export class SimTokens extends Tokens {
    * Binds the given token to the host.
    */
   public bindValue(host: IInflightHost, value: any) {
-    if (!(host instanceof Function)) {
```
Comment (tsuf239) [inline libs/wingsdk/src/target-sim/tokens.ts:64]: I wonder if it'll be better to remove this restriction only on the sim right now (because it was tested only for the sim) and to open an issue for the rest of the targets

File: libs/wingsdk/src/std/resource.ts [hunk 2]
```diff
@@ -14,6 +14,11 @@ export interface IInflightHost extends IResource {
    * Adds an environment variable to the host.
    */
   addEnvironment(name: string, value: string): void;
+
+  /**
+   * Returns the set of environment variables for this host.
+   */
+  get env(): Record<string, string>;
```
Comment (tsuf239) [inline libs/wingsdk/src/std/resource.ts:21]: This is nice :)  I'm just not sure if any resource can hold an `env`, maybe you can add it only to the container for now?

File: libs/wingsdk/src/target-sim/tokens.ts (hunk 1 above)
Comment (tsuf239) [reply libs/wingsdk/src/target-sim/tokens.ts:64]: maybe we can also narrow the restriction to NOT function and NOT a container? (instead of removing it completely?)

File: libs/wingsdk/src/target-sim/tokens.ts [hunk 3]
```diff
@@ -61,8 +61,10 @@ export class SimTokens extends Tokens {
...
```
Comment (Chriscbr) [inline libs/wingsdk/src/target-sim/tokens.ts:64]: I think it's ok to remove this check now since we recently added the capability in the SDK that all IInflightHost are expected to implement addEnvironment - which is all the tokenizer needs.

**Review by Chriscbr — APPROVED** [review]

File: libs/wingsdk/src/std/resource.ts (hunk 2 above)
Comment (Chriscbr) [reply libs/wingsdk/src/std/resource.ts:21]: Let's try to avoid adding direct `env` access in `IInflightHost` if it's possible for now. Accessing the environment variables be error prone since when you write `let x = host.env();` in userland, it's possible someone else will call `addEnvironment(...)` on the host afterwards, but then `x` will not reflect the new environment variable, leading to hard to find bugs.

File: libs/wingsdk/src/target-sim/tokens.ts (hunk 3 above)
Comment (Chriscbr) [reply libs/wingsdk/src/target-sim/tokens.ts:64]: Over here:
```js
        const envName = this.envName(value);
        // the same token might be bound multiple times by different variables/inflight contexts
        if (host.env[envName] === undefined) {
          host.addEnvironment(envName, value);
        }
```

What if we change `addEnvironment` so you can call it multiple times with the same key, as long as the value that is already stored is the same? I'm not sure but I wonder if this could solve the use case

```js
host.addEnvironment("foo", "bar");
host.addEnvironment("foo", "bar"); // OK
host.addEnvironment("foo", "baz"); // runtime error!
```

Comment (Chriscbr) [reply libs/wingsdk/src/target-sim/tokens.ts:64]: https://github.com/winglang/wing/pull/4379

**Review by eladb — COMMENTED** [review]
Nice
