### PR TITLE
fix(compiler): equality and external libraries bugs in simulator

### LINKED ISSUE #1980: cloud.Function timeout not working in simulator - vm.runInContext doesn't seem to kill the function
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

run a cloud function with a timeout set to 1s, that is calling a timeout of 1.5s.
```
bring cloud;

let c = new cloud.Counter();

resource Helper {
  init () {}
  extern "./sleep.js" inflight sleep(time_ms: num);
}

let helper = new Helper();

let f = new cloud.Function(inflight () => {
  // call sleep
  helper.sleep(1500);
  c.inc();
}, cloud.FunctionProps {timeout: 1s});

// doesn't work yet- see issue: 
new cloud.Function(inflight () => {
try{
  f.invoke("");
} catch (err) {}
  assert(c.peek() == 0);
}) as "test:function timeout";
```

### I expected this:

The process that the function is running on stops, and an error is thrown.

### Instead, this happened:

The function exceeded the timeout. No error was thrown.
it happened because of vm.runInContext doesn't "wait" for the inflight code to run, but executes it synchronically (without "await"). We suspect it runs on a different process and is not interrupted by the timeout completion.

### Is there a workaround?

_No response_

### Component:

SDK

### Wing Version:

_No response_

### Node.js Version:

_No response_

### Platform(s):

_No response_

### Anything else?

_No response_

### LINKED ISSUE #4118: Assertion failed for code that works once compiled to JS
#### app.w
```
let j = Json { hello: 123, world: [1, 2, 3] };
assert(Json.values(j) == [Json 123, Json [1, 2, 3]]);
```
I run this command:
```sh
wing compile app.w
```

### This happened:

```
ERROR: assertion failed: Json.values(j) == [Json 123, Json [1, 2, 3]]

target/app2.wsim.961063.tmp/.wing/preflight.js:9
       super(scope, id);
       const j = ({"hello": 123,"world": [1, 2, 3]});
>>     {((cond) => {if (!cond) throw new Error("assertion failed: Json.values(j) == [Json 123, Json [1, 2, 3]]")})((((a,b) => { try { return require('assert').deepStrictEqual(a,b) === undefined; } catch { return false; } })((Object.values(j)),[123, [1, 2, 3]])))};
     }
   }
```

### I expected this:

I expected Wing assertion to work, because the compiled JS code doesn't throw any error when pasted into Node.js REPL.

#### preflight.js
```
const j = ({"hello": 123,"world": [1, 2, 3]});
{((cond) => {if (!cond) throw new Error("assertion failed: Json.values(j) == [Json 123, Json [1, 2, 3]]")})((((a,b) => { try { return require('assert').deepStrictEqual(a,b) === undefined; } catch { return false; } })((Object.values(j)),[123, [1, 2, 3]])))};
```

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #4131: extern functions behave differently in Wing simulator
### I tried this:

I made a Wing project with these two files, and ran `wing test`:
```js
// main.w
class Util {
  extern "./superjson.js" static inflight dostuff();
}

test "superjson" {
  Util.dostuff();
}

// superjson.js
const superjson = require("superjson");

exports.dostuff = function() {
    const string = superjson.stringify(
        { handle: 'sim-3', method: 'dec', args: [ undefined, 'my-key' ] }
    );
    console.log(string);
}
```

### This happened:

This is printed by the test:
```
{"json":{"handle":"sim-3","method":"dec","args":[null,"my-key"]},"meta":{"referentialEqualities":{}}}
```

### I expected this:

I expected the output to match the output when I run `superjson` in a Node REPL:

```
Welcome to Node.js v18.14.1.
Type ".help" for more information.
> require("superjson").stringify({ handle: 'sim-3', method: 'dec', args: [ undefined, 'my-key' ] })
'{"json":{"handle":"sim-3","method":"dec","args":[null,"my-key"]},"meta":{"values":{"args.0":["undefined"]}}}'
```

Notice that the "meta" value contains an annotation saying that args.0 needs to be parsed as "undefined" instead of null. This annotation is not added when running in Wing simulator.

### Is there a workaround?

_No response_

### Component

SDK

### Wing Version

0.29.11

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #4725: Run `cloud.Function` outside of NodeJS vm sandbox
### Feature Spec

When invoking a `cloud.Function` in the simluator, an isolated worker/process is spawned to do the work. This should work/feel similar to simply running the inflight code in a new nodejs process.

### Use Cases

Provides a more realistic experience of running JS like you might experience on serverless platforms.

Will fix bugs relating to using VM sandboxes like:
- https://github.com/winglang/wing/issues/1980
- https://github.com/winglang/wing/issues/4131
- https://github.com/winglang/wing/issues/4118

### Implementation Notes

Depends on https://github.com/winglang/wing/pull/4697

The two primary options are
- Create an entirely new child process to invoke the `cloud.Function` by just running `node` with arguments
- (ideal, imo) Use https://nodejs.org/api/worker_threads.html as a means to isolate work. While this does not give us process isolation, it should isolate everything else. We can then use SharedArrayBuffer to communicate with the simulator by default (very fast), falling back to HTTP otherwise.

### Component

SDK

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.
* If this issue is labeled **needs-discussion**, it means the spec has not been finalized yet. Please reach out on the #dev channel in the [Wing Slack](https://t.winglang.io/slack).

### LINKED ISSUE #4792: `expect.equal(json1, json2)` fails with `Values have same structure but are not reference-equal`
### I tried this:

The `expect.equal()` method is failing because of https://github.com/winglang/wing/issues/4118

### This happened:

Something like this:

```
     │ AssertionError [ERR_ASSERTION]: Values have same structure but are not reference-equal:
     │ 
     │ {
     │   producer_result: {
     │     result: 12
     │   }
     │ }
     │ 
     │     at Util.equal (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-XhI7xo/index.js:5449:26)
     │     at $Closure1.handle (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-XhI7xo/index.js:34:38)
     │     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
     └     at async exports.handler (/var/folders/vm/cm444l3124j_vh_8rkhz6kqm0000gn/T/wing-bundles-XhI7xo/index.js:5685:10)
 
```

### I expected this:

To work

### Is there a workaround?

stringify the objects

### Component

SDK

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

@skorfmann until we fix the VM issue that's the root cause, let's just change the expect.equal library to use `JSON.stringify()` in case it compares to objects, ok?

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
This pull request fixes a range of funky JavaScript issues we've had running inflight code in the Wing simulator by switching internally from running JS code in a `vm` to running JS code using Node.js child processes.

The main issues with `vm` are:
- several third-party JavaScript dependencies behave differently when executed inside a `vm` and outside. This may be related to differences in vm behavior as described in https://github.com/nodejs/node/issues/28823
- we cannot easily stop/kill code executing in a `vm` process, making it impossible to simulate cloud.Function timeouts

Fixes #1980
Fixes #4131
Fixes #4118
Fixes #4792

Closes #4725

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Review by MarkMcCulloh — COMMENTED** [review]
Very exciting! This PR supercedes https://github.com/winglang/wing/pull/5547 right?

btw, on the note of worker vs child process: One of the big optimization options with workers is that you can share memory between them and the host, so we can use SharedArrayBuffer as a way to do fast (and still serialized) communication.

Might be an interesting future optimization, but cp makes sense now too

File: libs/wingsdk/src/shared/stream-processor.ts [hunk 1]
```diff
@@ -0,0 +1,41 @@
+import { Readable } from "stream";
+import { StringDecoder } from "string_decoder";
+
+export function processStream(
```
Comment (Chriscbr) [inline libs/wingsdk/src/shared/stream-processor.ts:4]: Docstring

File: libs/wingsdk/src/target-sim/service.inflight.ts [hunk 2]
```diff
@@ -5,23 +5,23 @@ import {
...
+  private readonly sandbox: LegacySandbox;
   private running: boolean = false;
   private onStop?: IServiceStopHandlerClient;
 
   constructor(props: ServiceSchema["props"], context: ISimulatorContext) {
     this.context = context;
     this.entrypoint = resolve(context.simdir, props.sourceCodeFile);
     this.autoStart = props.autoStart;
-    this.sandbox = new Sandbox(this.entrypoint, {
+    this.sandbox = new LegacySandbox(this.entrypoint, {
```
Comment (Chriscbr) [inline libs/wingsdk/src/target-sim/service.inflight.ts:24]: Open an issue about this (cloud.Service can't use the updated Sandbox because the API tries sending a function closure across HTTP)

**Comment by Chriscbr** [comment]
@MarkMcCulloh yep, I think this can supersede the other PR assuming the approach makes sense to y'all.

> btw, on the note of worker vs child process: One of the big optimization options with workers is that you can share memory between them and the host, so we can use SharedArrayBuffer as a way to do fast (and still serialized) communication.

Interesting, yeah I see how that could give us some efficiency gains. It would be interesting to do some profiling on wing programs to see how much time is spent computing vs on IPC/HTTP etc.

File: libs/wingsdk/src/target-sim/service.inflight.ts (hunk 2 above)
Comment (eladb) [reply libs/wingsdk/src/target-sim/service.inflight.ts:24]: Any thoughts on how to address this?

File: examples/tests/valid/inflight_handler_singleton.test.w [hunk 3]
```diff
@@ -36,11 +40,21 @@ test "single instance of Foo" {
...
   expect.equal(z, "100-fn2"); // fn2 should have a separate instance
 
-  // the simulator intentionally reuses the sandbox across invocations
-  // but we can't trust that this will always happen on the cloud
-  if sim {
-    expect.equal(y, "101");
-    expect.equal(z, "100-fn2"); // fn2 should have a separate instance
-    log("client has been reused");
-  }
+  // y could be 100 or 101 depending on whether the execution environment
```
Comment (eladb) [inline examples/tests/valid/inflight_handler_singleton.test.w:43]: 👍

File: libs/wingsdk/src/shared/sandbox.ts [hunk 4]
```diff
@@ -12,8 +14,138 @@ export interface SandboxOptions {
...
+
+  constructor(entrypoint: string, options: SandboxOptions = {}) {
+    this.entrypoint = entrypoint;
+    this.options = options;
+    this.createBundlePromise = this.createBundle();
+  }
+
+  public async cleanup() {
+    for (const timeout of this.timeouts) {
+      clearTimeout(timeout);
```
Comment (eladb) [inline libs/wingsdk/src/shared/sandbox.ts:46]: what happens if there's a `setInterval` somewhere?

File: libs/wingsdk/src/shared/sandbox.ts [hunk 5]
```diff
@@ -12,8 +14,138 @@ export interface SandboxOptions {
...
+
+  private async createBundle() {
+    const workdir = await mkdtemp(path.join(tmpdir(), "wing-bundles-"));
+
+    // wrap contents with a shim that handles the communication with the parent process
+    // we insert this shim before bundling to ensure source maps will work correctly
+    let contents = (await readFile(this.entrypoint)).toString();
+
+    // log a warning if contents includes __dirname or __filename
+    if (contents.includes("__dirname") || contents.includes("__filename")) {
```
Comment (eladb) [inline libs/wingsdk/src/shared/sandbox.ts:58]: this will only catch refs to `__dirname` and `__filename` at the root module, no required modules.

File: libs/wingsdk/src/target-sim/service.inflight.ts (hunk 2 above)
Comment (Chriscbr) [reply libs/wingsdk/src/target-sim/service.inflight.ts:24]: Probably https://github.com/winglang/wing/issues/4781

File: examples/tests/valid/inflight_handler_singleton.test.w [hunk 6]
```diff
@@ -36,11 +40,21 @@ test "single instance of Foo" {
...
+  let n = foo.inc();
+  util.sleep(3s);
+  assert(n == foo.get());
+}) as "incAndCheck";
+
+test "Foo state is not shared between concurrent function invocations" {
+  // start two invocations of fn, staggering them by 1 second
+  incAndCheck.invokeAsync("");
+  util.sleep(1s);
+  incAndCheck.invoke("");
```
Comment (eladb) [inline examples/tests/valid/inflight_handler_singleton.test.w:59]: nit:

```suggestion
  incAndCheck.invokeAsync();
  util.sleep(1s);
  incAndCheck.invoke();
```

**Review by eladb — APPROVED** [review]
Looking forward for this one!

File: libs/wingsdk/src/shared/sandbox.ts (hunk 4 above)
Comment (Chriscbr) [reply libs/wingsdk/src/shared/sandbox.ts:46]: explain?

File: libs/wingsdk/src/shared/sandbox.ts (hunk 5 above)
Comment (Chriscbr) [reply libs/wingsdk/src/shared/sandbox.ts:58]: I'm aware (but don't know of any other solutions)

File: tools/hangar/__snapshots__/error.ts.snap
Comment (Chriscbr) [inline tools/hangar/__snapshots__/error.ts.snap:1]: Fixing...

File: libs/wingsdk/src/shared/bundling.ts [hunk 7]
```diff
@@ -72,13 +72,13 @@ export function createBundle(
...
-    sourcemapData.sourceRoot = normalPath(sourcemapData.sourceRoot);
+    sourcemapData.sourceRoot = normalPath(resolve(sourcemapData.sourceRoot));
   }
 
   for (const [idx, source] of Object.entries(
     sourcemapData.sources as string[]
   )) {
-    sourcemapData.sources[idx] = normalPath(source);
+    sourcemapData.sources[idx] = normalPath(resolve(source));
   }
```
Comment (Chriscbr) [inline libs/wingsdk/src/shared/bundling.ts:82]: Without this change, source paths were getting messed up on my system, causing the files to not be found - I was getting stack traces like this:

```
fail ┌ inflight_stacktraces.test.wsim » root/env0/test:assert
     │ child process.argv: [
     │   '/Users/chrisr/.volta/tools/image/node/20.11.0/bin/node',
     │   '/var/folders/q3/0yxxhjr95vx4yfkk3lvy6dj40000gn/T/wing-bundles-gefQdo/index.js'
     │ ]
     │ Error: assertion failed: false
     │ at /private/Users/chrisr/dev/wing1/examples/tests/error/inflight_stacktraces.test.w:7:3
     │ at handler /private/Users/chrisr/dev/wing1/examples/tests/error/target/test/inflight_stacktraces.test.wsim/.wing/handler_c8b175d2.sandbox.js:19:25
     └ at /private/Users/chrisr/dev/wing1/examples/tests/error/target/test/inflight_stacktraces.test.wsim/.wing/handler_c8b175d2.sandbox.js:24:19
```

I might be doing something wrong though

Comment (Chriscbr) [reply libs/wingsdk/src/shared/bundling.ts:82]: Hmm, this only fixes it when I run via the compiled Wing CLI and not when it's run by the hangar.

File: tools/hangar/__snapshots__/error.ts.snap [hunk 8]
```diff
@@ -26,7 +26,9 @@ exports[`inflight_stacktraces.test.w 1`] = `
      │   | test \\"assert\\" {
      │ 7 |   assert(false);
      │   |   ^
-     └ at <ABSOLUTE>/inflight_stacktraces.test.w:7:3
+     │ at <ABSOLUTE>/inflight_stacktraces.test.w:7:3
+     │ at handler <ABSOLUTE>/handler_c8b175d2.sandbox.js:18:25
+     └ at <ABSOLUTE>/handler_c8b175d2.sandbox.js:23:19
```
[the remark this answers is not in the document]
Comment (Chriscbr) [reply tools/hangar/__snapshots__/error.ts.snap:31]: Ah, yeah I think that's a good callout, I don't see a reason why we need to show these lines (at least for the default output)
