### PR TITLE
fix(sdk): use lockfiles to prevent multiple simulators on the same state directory

### LINKED ISSUE #5799: `wing it` in the same directory uses the same state directory
### I tried this:

Running `wing it` twice in the same directory

### This happened:

The simulations use the same state files

### I expected this:

I expected the simulation runs to use separate state, or to see a warning / error of some kind.

Each simulated resource is manages its own simulated files, and having more than one simulation of the same resource touching the same files may result in race conditions, data loss, or hard to resolve bugs.

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

0.59.12

### Node.js Version

20.11.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by skyrpex**
Uses a lockfile to prevent multiple simulators on the same state directory, which would cause issues. The lockfile is periodically updated in order to check for staleness.

Additionally, adds a `--statedir "mystatedir"` flag to `wing it` that allows users changing the simulator state directory.

Fixes #5799.

### CODE REVIEW

File: libs/wingsdk/src/simulator/simulator.ts [hunk 1]
```diff
@@ -314,6 +323,36 @@ export class Simulator {
...
   }
 
+  private async acquireStateLock() {
+    if (this.lockfile) {
+      return; // already locked
+    }
+
+    await mkdir(this.statedir, { recursive: true });
+    try {
+      this.lockfile = await openFileHandle(this.lockfileFilename, "wx");
```
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/simulator.ts:333]: I wonder what we can do to make the mechanism more robust to crashes (maybe storing a process ID or timestamp inside that can be read? not sure)

File: libs/wingsdk/src/simulator/simulator.ts
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/simulator.ts:1]: Test?

**Review by Chriscbr — APPROVED** [review]

File: libs/wingsdk/src/simulator/simulator.ts (hunk 1 above)
Comment (skyrpex) [reply libs/wingsdk/src/simulator/simulator.ts:333]: I've been looking out there and found https://www.npmjs.com/package/proper-lockfile. They check for staleness by constantly updating the lockfile, and use `mkdir` instead of `open` to make it network-compatible.

Not sure how a process ID in the lockfile would help, though.

I think we are good if we just implement the staleness check. No need for network compatibility, IMO. What do you think?

File: libs/wingsdk/src/simulator/simulator.ts
Comment (skyrpex) [reply libs/wingsdk/src/simulator/simulator.ts:1]: On it 💪🏻

File: libs/wingsdk/src/simulator/simulator.ts (hunk 1 above)
Comment (Chriscbr) [reply libs/wingsdk/src/simulator/simulator.ts]: Oh I see, so basically checking if it's stale based on its timestamp. That sounds good to me 👍

File: libs/wingsdk/src/simulator/lockfile.ts [hunk 2]
```diff
@@ -0,0 +1,125 @@
...
+    return false;
+  }
+};
+
+const UPDATE_INTERVAL = 1000;
+const STALE_THRESHOLD = 5000;
+
+export interface LockfileProps {
+  readonly path: string;
+  readonly onCompromised?: () => void;
```
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/lockfile.ts:21]: Maybe this can be async?

File: libs/wingsdk/src/simulator/simulator.ts [hunk 3]
```diff
@@ -225,9 +226,17 @@ export class Simulator {
...
 
+  private lockfile: Lockfile;
+
   constructor(props: SimulatorProps) {
     const simdir = resolve(props.simfile);
     this.statedir = props.stateDir ?? join(simdir, ".state");
+    this.lockfile = new Lockfile({
+      path: join(this.statedir, ".lock"),
+      onCompromised: () => {
+        this.stop().catch(() => {});
```
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/simulator.ts:237]: This would cause any exceptions raised by stop() to be caught / hidden from the user, I wonder if we should avoid that? Maybe
```suggestion
        void this.stop();
```

File: libs/wingsdk/src/simulator/lockfile.ts [hunk 4]
```diff
@@ -0,0 +1,125 @@
...
+  try {
+    await fs.stat(path);
+    return true;
+  } catch {
+    return false;
+  }
+};
+
+const UPDATE_INTERVAL = 1000;
+const STALE_THRESHOLD = 5000;
```
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/lockfile.ts:17]: (optional) Add a short description for each?

File: libs/wingsdk/src/simulator/lockfile.ts [hunk 5]
```diff
@@ -0,0 +1,125 @@
...
+          if (this.lastMtime) {
+            try {
+              const stats = await fs.stat(this.path);
+              if (stats.mtimeMs !== this.lastMtime) {
+                this.markAsCompromised(
+                  "Lockfile was updated by another process"
+                );
+                return;
+              }
+            } catch (_error) {
```
Comment (Chriscbr) [inline libs/wingsdk/src/simulator/lockfile.ts:85]: Maybe it's PTSD but I get weary whenever we're dropping error information since the only other way for a user to get it would be to change the source code and rebuild the project. Can we log the original error some way? (perhaps only if DEBUG=1 or something...)

File: libs/wingsdk/src/simulator/lockfile.ts [hunk 6]
```diff
@@ -0,0 +1,125 @@
...
+    if (await exists(this.path)) {
+      try {
+        const stats = await fs.stat(this.path);
+        if (Date.now() - stats.mtimeMs > STALE_THRESHOLD) {
+          await fs.rm(this.path);
+        }
+      } catch (error) {
+        throw new Error("Failed to check lockfile status: " + error);
+      }
+    }
```
[the remark this answers is not in the document]
Comment (Chriscbr) [reply libs/wingsdk/src/simulator/lockfile.ts:53]: I suppose there could be an edge case where the file exists but the permission has changed.

**Review by Chriscbr — APPROVED** [review]

File: libs/wingsdk/src/simulator/lockfile.ts (hunk 6 above)
[the remark this answers is not in the document]
Comment (skyrpex) [reply libs/wingsdk/src/simulator/lockfile.ts:53]: I guess we could assume it got compromised then, too?

File: libs/wingsdk/src/simulator/simulator.ts (hunk 3 above)
Comment (skyrpex) [reply libs/wingsdk/src/simulator/simulator.ts:237]: My intention was to hide problems like "Can't stop simulator if it's not running" but that should never happen in the first place... So good call, will remove that.

File: libs/wingsdk/src/simulator/lockfile.ts (hunk 2 above)
Comment (skyrpex) [reply libs/wingsdk/src/simulator/lockfile.ts:21]: Yeah, will change it.

File: libs/wingsdk/src/simulator/lockfile.ts (hunk 5 above)
Comment (skyrpex) [reply libs/wingsdk/src/simulator/lockfile.ts:85]: 👍🏻 I believe there's already a log mechanism in place, will have a look.

Comment (skyrpex) [reply libs/wingsdk/src/simulator/lockfile.ts]: Now, if there's a related error, it's passed to the onCompromised callback so the simulator can log it.

File: libs/wingsdk/src/simulator/lockfile.ts (hunk 4 above)
Comment (skyrpex) [reply libs/wingsdk/src/simulator/lockfile.ts]: Done.

File: libs/wingsdk/src/simulator/simulator.ts (hunk 3 above)
Comment (skyrpex) [reply libs/wingsdk/src/simulator/simulator.ts]: The simulator now logs these errors too 👍🏻

**Review by polamoros — APPROVED** [review]
