### PR TITLE
fix(compiler)!: unexpected heuristic for inference across scopes

### LINKED ISSUE #4438: Unable to infer type, but it's previously inferred
### I tried this:

Given `main.w`:

```ts
bring cloud;

struct GitHubTokens {
  access_token: str;
  expires_in: num;
  refresh_token: str;
  refresh_token_expires_in: num;
  token_type: str;
  scope: str;
}

let exchangeCodeForTokens = inflight (code: str) => {
  return GitHubTokens.fromJson("");
};

let handler = inflight (request: cloud.ApiRequest) => {
  let tokens = exchangeCodeForTokens("code");
};
```

Run `wing compile main.w`.

### This happened:

```
error: Unable to infer type
   --> main.w:17:7
   |
17 |   let tokens = exchangeCodeForTokens("code");
   |       ^^^^^^ Unable to infer type
```

### I expected this:

It should infer the type, since it's already know if you hover on `exchangeCodeForTokens`.

### Is there a workaround?

Explicitely define the return type as `GitHubTokens`.

### Component

Compiler

### Wing Version

0.35.5

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #4438

Due to:
- breadth-first type checking
- simplistic inference
- no re-checking (good)

Currently, this works:

```
let f = (arg) => {
  return arg.get("a");
};

if true {
  let x = f({ a: true });
}
```

but this does not work:

```
let f = () => {
  return { a: true };
};

if true {
  let x = f().get("a");
//        ^^^ don't know what the return type is yet because the closure above hasn't be checked
}
```

Because when first implementing inference, the sub-scopes of a scope were checked in reverse order. I thought this heuristic was kinda neat and figured it had legs. Now I'm thinking that was wrong. 

With this PR, the scope will be checked in normal order. Now the second case will work and the first case above will **not** work. It will require explicit annotation on the argument:

```
let f = (arg: Json) => {
  return arg.get("a");
};

if true {
  let x = f({ a: true });
}
```

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

BREAKING CHANGE: Inference now prioritizes earlier scopes rather than later ones. This previously allowed closures called from other scopes to leave off argument type annotations. [This](https://github.com/winglang/wing/blob/fcfc3462d37a063d96d49b4105e27466ff7793c8/examples/tests/invalid/inference.test.w#L106) is an example of a case that previously worked.

### CODE REVIEW

File: libs/wingc/src/type_check/inference_visitor.rs [hunk 1]
```diff
@@ -187,3 +187,32 @@ impl<'a> crate::visit_types::VisitType<'_> for InferenceVisitor<'a> {
 		}
 	}
 }
+
+#[derive(Default)]
+/// Deeply visits a type and finds any inferences.
+pub struct InferenceCounterVisitor {
```
Comment (MarkMcCulloh) [inline libs/wingc/src/type_check/inference_visitor.rs:193]: ℹ️ I created this during some other experiments while researching the issue. It's not functionally different than the previous visitor for the use-case of looking for inferences. It's just more efficient and has no `mut`s anywhere.

File: examples/tests/invalid/inference.test.w [hunk 2]
```diff
@@ -96,3 +96,19 @@ let badFunc: inflight (str): void = inflight (arg1: num) => {};
...
+
+let unknownArg = (arg) => {
+//                ^^^ Unable to infer type
+  return arg.get("a");
+//           ^^^ Property not found
+};
+
+if true {
+  unknownArg({ a: true });
+}
```
Comment (Chriscbr) [inline examples/tests/invalid/inference.test.w:114]: If I understand correctly, this is an only an invalid in the sense that our inference system isn't strong enough to analyze it, not because there's a logical error/bug in the code, right?

If that's the case I don't know if it should be flagged as an invalid case given we might want to support it in the future. (Or maybe we can leave it and link to the issue about implementing better inference?)

**Review by Chriscbr — APPROVED** [review]

File: examples/tests/invalid/inference.test.w (hunk 2 above)
Comment (MarkMcCulloh) [reply examples/tests/invalid/inference.test.w:114]: Yep that's right.

I think there's value in showing this case, since we also want to validate behavior that shouldn't work. This ensures it doesn't change in unexpected ways. I'll add an issue and link to it though.
