### PR TITLE
fix(cli): `wing pack` does not respect `-o` for custom output filename

### LINKED ISSUE #4796: `wing pack` doesn't respect `-o`
### I tried this:

```sh
wing pack -o foo.tgz
```

### This happened:

Output was still the original name

### I expected this:

That the output will be `foo.tgz`

### Is there a workaround?

_No response_

### Component

CLI

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by garysassano**
Closes #4796

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: apps/wing/src/cli.ts [hunk 1]
```diff
@@ -207,7 +207,7 @@ async function main() {
   program
     .command("pack")
     .description("Package the current directory into an npm library (gzipped tarball).")
-    .addOption(new Option("-o --out-file <filename>", "Output filename"))
+    .addOption(new Option("-o --outfile <filename>", "Output filename"))
```
Comment (MarkMcCulloh) [inline apps/wing/src/cli.ts:210]: Could you add a test?

File: apps/wing/src/cli.ts [hunk 2]
```diff
@@ -207,7 +207,7 @@ async function main() {
   program
     .command("pack")
     .description("Package the current directory into an npm library (gzipped tarball).")
-    .addOption(new Option("-o --out-file <filename>", "Output filename"))
```
Comment (MarkMcCulloh) [inline apps/wing/src/cli.ts:210]: This fixes the issue because the interface name doesn't match, right? Could we change the interface instead of this? IMO I like out-file better, so maybe the JS side needs to be outFile.

**Review by MarkMcCulloh — APPROVED** [review]
