### PR TITLE
fix(compiler): phase mismatch not stated explicitly

### LINKED ISSUE #2230: inflight/preflight type mismatch error ergonomic improvements
### I tried this

Implement `IFunctionHandler` but forgot to indicate that `handle` is `inflight`.
Used this code:
```ts
bring cloud;

class Handler impl cloud.IFunctionHandler {
  pub handle(event: str) {

  }
}
```
Instead of this (forgot to add the `inflight` modifier on the `handle` method):
```ts
bring cloud;

class Handler impl cloud.IFunctionHandler {
  pub inflight handle(event: str) {

  }
}
```

### I expected this:

If the types only differ in their inflight / preflight - the error should say it explicitly

### Instead, this happened
```sh
error: Expected type to be "inflight (event: str): void", but got "preflight (event: str): void" instead
  --> wing/main.w:3:7
  |
3 | class Handler impl cloud.IFunctionHandler {
  |       ^^^^^^^ Expected type to be "inflight (event: str): void", but got "preflight (event: str): void" instead
```

### Is there a workaround?

N/A

### Component

Compiler

### Wing Version

0.33.1

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Lancear**
Closes #2230 

- Adds the phase mismatch hint when none of the expected types match the phase that was given

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Docs updated (only required for features)
- [x] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

**Comment by Lancear** [comment]
will add tests tomorrow

File: tools/hangar/__snapshots__/invalid.ts.snap [hunk 1]
```diff
@@ -793,14 +793,14 @@ Duration <DURATION>"
 `;
 
 exports[`cloud_function_expects_inflight.test.w 1`] = `
-"error: Expected type to be \\"inflight (event: str): void\\", but got \\"preflight (name: str): str\\" instead
+"error: Expected phase to be preflight, but got inflight instead
```
Comment (Chriscbr) [inline tools/hangar/__snapshots__/invalid.ts.snap:796]: Looks like the error message got swapped around - it should say that the expected phase is "inflight"

File: examples/tests/invalid/phase_mismatch.test.w [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+
+let my_func2 = (callback: (num): num) => {  };
+my_func2(inflight (n: num): num => { return n * 2; });
+
+interface IMyHandlerInterface1 {
+  inflight handle(n:  num): num;
+}
+
+let my_func3 = (callback: IMyHandlerInterface1) => {  };
+my_func3((n: num): num => { return n * 2; });
```
Comment (Chriscbr) [inline examples/tests/invalid/phase_mismatch.test.w:12]: What happens if the phases don't match and the argument types are incompatible? (can we add a test?)

File: examples/tests/invalid/phase_mismatch.test.w
Comment (Chriscbr) [inline examples/tests/invalid/phase_mismatch.test.w:1]: What happens if the phase mismatch is not the "top-most" error? for example:

```js
bring cloud;

let accepts_callback = (callback: (inflight (str): str): void): void => {
  callback(inflight (msg: str): str => {
    return "Hi " + msg + "!";
  });
};

let callback = (inner_fn: ((str): str): void): void => {};

accepts_callback(callback); // error
```

On the last line, the expected type is `preflight (inflight (str): str): void` but the function passed was type `preflight (preflight (str): str): void`.

File: tools/hangar/__snapshots__/invalid.ts.snap (hunk 1 above)
Comment (Chriscbr) [inline tools/hangar/__snapshots__/invalid.ts.snap:796]: I feel a bit mixed on this new error because we're subtracting information away from the user. IMO we should try to find some way to highlighting the phase mismatch while still showing the expected and found types.

Two ideas that come to mind:

1) add on to the beginning of the error

```
error: Mismatched function phase; expected type to be "inflight (event: str): void", but got "preflight (name: str): str" instead
```

2) add the information as a separate error hint (see https://github.com/winglang/wing/issues/4503):

```
error: Expected type to be "inflight (event: str): void", but got "preflight (name: str): str" instead
  <code excerpt>
  hint: Expected phase to be inflight, but got preflight instead
```

What do you think about these alternatives?

(cc @MarkMcCulloh about error message style)

**Review by Chriscbr — CHANGES_REQUESTED** [review]

File: tools/hangar/__snapshots__/invalid.ts.snap (hunk 1 above)
Comment (Lancear) [reply tools/hangar/__snapshots__/invalid.ts.snap:796]: nice catch

Comment (Lancear) [reply tools/hangar/__snapshots__/invalid.ts.snap:796]: I think this would work great as a hint to the existing type mismatch error 👍

File: examples/tests/invalid/phase_mismatch.test.w (hunk 2 above)
Comment (Lancear) [reply examples/tests/invalid/phase_mismatch.test.w:12]: currently it would result in a type mismatch. phase mismatch is currently checked as "would the type match when we dont look at the phase"  instead of checking if the phases mismatch. Especially when we go the hint route we could simply check if the phase mismatch and add the hint, would make the check also easier.

File: tools/hangar/__snapshots__/invalid.ts.snap (hunk 1 above)
Comment (staycoolcall911) [reply tools/hangar/__snapshots__/invalid.ts.snap:796]: Hint sounds great.

File: examples/tests/invalid/phase_mismatch.test.w (hunk 2 above)
Comment (Lancear) [reply examples/tests/invalid/phase_mismatch.test.w:12]: changed this to always show the hint when the expected types include no function with the given phase, thus also if the argument types mismatch. added a test for this.

File: examples/tests/invalid/phase_mismatch.test.w
Comment (Lancear) [reply examples/tests/invalid/phase_mismatch.test.w:1]: only checked if top-most error atm. added this case to the tests

File: tools/hangar/__snapshots__/invalid.ts.snap (hunk 1 above)
Comment (Lancear) [reply tools/hangar/__snapshots__/invalid.ts.snap]: switched it to a hint like the others around it, now looking into the cli/lsp changes that need to be done for #4503

Comment (Lancear) [reply tools/hangar/__snapshots__/invalid.ts.snap]: added hints to diagnostics and tried to update the cli and lsp accordingly

File: tools/hangar/__snapshots__/invalid.ts.snap [hunk 3]
```diff
@@ -2335,11 +2339,13 @@ Duration <DURATION>"
...
 exports[`nil.test.w 1`] = `
-"error: Expected type to be \\"str\\", but got \\"nil\\" instead (hint: to allow \\"nil\\" assignment use optional type: \\"str?\\")
+"error: Expected type to be \\"str\\", but got \\"nil\\" instead
   --> ../../../examples/tests/invalid/nil.test.w:3:14
   |
 3 | let x: str = nil;
-  |              ^^^ Expected type to be \\"str\\", but got \\"nil\\" instead (hint: to allow \\"nil\\" assignment use optional type: \\"str?\\")
+  |              ^^^ Expected type to be \\"str\\", but got \\"nil\\" instead
+  |
+  = hint: to allow \\"nil\\" assignment use optional type: \\"str?\\"
```
Comment (Chriscbr) [inline tools/hangar/__snapshots__/invalid.ts.snap:2348]: Thank you for updating these other spots in the code as well!

**Review by Chriscbr — APPROVED** [review]
Great work @Lancear! LGTM

**Review by polamoros — APPROVED** [review]
