### PR TITLE
fix(console): console log levels are not persistent across restarts

### LINKED ISSUE #2806: Console log levels are not persistent across restarts
### I tried this:

Changed log level
Restarted the console

### This happened:

Log level reverted to default

### I expected this:

Log level to persist

### Is there a workaround?

_No response_

### Component

Wing Console

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

Related to #2552

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by eladcon**
Using local storage to save some of the console view settings across app restarts

Fixes #2806

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: apps/wing-console/console/ui/src/use-localstorage.ts [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+  useLayoutEffect,
+  useEffect,
+  useMemo,
+} from "react";
+
+import { trpc } from "./trpc.js";
+
+const noop = () => {};
+
+export const useLocalStorage = <T>(
```
Comment (skyrpex) [inline apps/wing-console/console/ui/src/use-localstorage.ts:16]: We have `react-use` installed. Is it possible to use https://github.com/streamich/react-use/blob/master/docs/useLocalStorage.md?

**Comment by skyrpex** [comment]
I've noticed a delay in the stuff that uses the wingfile as part of the storage key... I'd like to avoid the delay, it feels very wrong.

Off the top of my head I think we could inject the wingfile into the HTML so it's available instantly to the JS.

File: apps/wing-console/console/ui/src/use-localstorage.ts [hunk 2]
```diff
@@ -0,0 +1,79 @@
...
+  key: string,
+  initialValue: T,
+): [T, Dispatch<SetStateAction<T>>, boolean, () => void] => {
+  const wingfileQuery = trpc["app.path"].useQuery();
+  const wingfile = useMemo(() => {
+    return wingfileQuery.data;
+  }, [wingfileQuery.data]);
+
+  return useLocalStorage(wingfile ? `${wingfile}.${key}` : key, initialValue);
+};
```
Comment (skyrpex) [inline apps/wing-console/console/ui/src/use-localstorage.ts:79]: I think we should change how this work a bit:

- Move the whole `wingfile` thing away
- Create a `AppLocalStorageProvider` that accepts a `storageKey` and setups a context with that key
- Change `useAppLocalStorage` so it uses the context above. If the context is not set, throw
- Use the `AppLocalStorageProvider` in the `Console.tsx` or `App.tsx` file, and display a loader until the `wingfile` isn't fetched
- Use a hash of `wingfile` as the `storageKey` instead of the whole `wingfile` string

Comment (skyrpex) [reply apps/wing-console/console/ui/src/use-localstorage.ts:79]: With the implementation above we will avoid:

- Random behavior meanwhile the wingfile is being fetched
- Making the `use-localstorage` too dependent on the `app.path` / `app.wingfile` key

**Review by skyrpex — CHANGES_REQUESTED** [review]

**Review by skyrpex — CHANGES_REQUESTED** [review]

**Review by skyrpex — APPROVED** [review]
