### PR TITLE
fix: process.stdout regression

### LINKED ISSUE #6928: Output via JavaScript integration broken in Wing 0.77.16
### I tried this:

I have been using a JavaScript function to create output without a newline (since `log` currently always includes one) for a long time. It stopped worked in `0.77.16`.

Here is a test program, `write.main.w`:

```
class Process {
  pub extern "./process-helper.js" static write(s: str);
}

log("== start ==");

log("");

Process.write("[[");
Process.write(" .. ");
Process.write(" .. ");
Process.write(" .. ");
Process.write("]]");

log("");

log("== end ==");
```

My support file, `process-helper.js`:

```
exports.write = function(s) {
  return process.stdout.write(s);
};
```

### This happened:

```
[univac]$ wing --version                          
0.77.16
[univac]$ wing compile write.main.w --platform sim
== start ==

[[
..
..
..
]]
== end ==
[univac]$ wing compile write.main.w --platform sim
== start ==

[[
..
..
..
]]
== end ==
[univac]$ wing compile write.main.w --platform sim
== start ==

[[
..
..
..
]]
== end ==
```

### I expected this:

```
[univac]$ wing --version
0.77.15
[univac]$ wing compile write.main.w --platform sim
== start ==

[[ ..  ..  .. ]]

== end ==
[univac]$ wing compile write.main.w --platform sim
== start ==

[[ ..  ..  .. ]]

== end ==
[univac]$ wing compile write.main.w --platform sim
== start ==

[[ ..  ..  .. ]]

== end ==
[univac]$ wing compile write.main.w --platform sim
== start ==

[[ ..  ..  .. ]]

== end ==
```

### Is there a workaround?

I have not found one. :-(

### Anything else?

_No response_

### Wing Version

0.77.16

### Node.js Version

v22.5.1

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #6928

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingcompiler/src/compile.ts [hunk 1]
```diff
@@ -134,7 +134,7 @@ export function determineTargetFromPlatforms(platforms: string[]): string {
  */
 export async function compile(entrypoint: string, options: CompileOptions): Promise<string> {
   const { log } = options;
-  const preflightLog = options.preflightLog ?? console.log;
+  const preflightLog = options.preflightLog ?? process.stdout.write.bind(process.stdout);
```
Comment (MarkMcCulloh) [inline libs/wingcompiler/src/compile.ts:137]: A test would be good to prevent this regression in the future

**Review by MarkMcCulloh — APPROVED** [review]

File: libs/wingcompiler/src/compile.ts (hunk 1 above)
Comment (Chriscbr) [reply libs/wingcompiler/src/compile.ts:137]: Added

**Review by skyrpex — APPROVED** [review]
