### PR TITLE
fix: unable to call static namespaced methods from inflight

### LINKED ISSUE #2576: Compiler panics when `util` is used inflight
### I tried this:

compiling the following code

```
bring cloud;
bring util;

let bucket = new cloud.Bucket();
let queue = new cloud.Queue();

queue.addConsumer(inflight (message: str) => {
  bucket.put("wing.txt", "Hello, ${message}");
});

// tests

class TestHelper {
  init(){}
  extern "./sleep.js" inflight sleep(milli: num);
}

let js = new TestHelper();

test "Hello, world!" {
  queue.push("world!");
  log("pushed");
  if  util.env("WING_TARGET") == "sim" {
    js.sleep(1000);
    log("sim");
  } else {
    log("something else");
    js.sleep(5000);
  }
  assert("Hello, world!" == bucket.get("wing.txt"));
}
```

### This happened:

It doesn't compile, but throws an error

```
wing test --target tf-aws main.w                                                                                                    
⠹ Compiling to tf-aws...thread '<unnamed>' panicked at 'Unexpected type: "Util" referenced inflight', libs/wingc/src/jsify.rs:1035:22
stack backtrace:
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/009b5606:wasm-function[242]:0xdd260)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/009b5606:wasm-function[1459]:0x182aad)
    at wingc::jsify::JSifier::jsify_statement::h54e46ec7800ead6f (wasm://wasm/009b5606:wasm-function[35]:0x524b2)
    at wingc_compile (wasm://wasm/009b5606:wasm-function[275]:0xea209)
    at wingc_compile.command_export (wasm://wasm/009b5606:wasm-function[1605]:0x188009)
    at Object.invoke (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/wingc.js:145:37)
    at compile (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/compile.js:125:38)
    at async withSpinner (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/util.js:30:24)
    at async testOne (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/test.js:49:22)
    at async test (/Users/sebastian/.nvm/versions/node/v18.16.0/lib/node_modules/winglang/dist/commands/test.js:44:9)
```

### I expected this:

- to compile successfully 
- in case of an error a stack trace to the exact code location to help me understand the error

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

0.17.11

### Wing Console Version

0.17.11

### Node.js Version

v18.16.0

### Platform(s)

MacOS

### Anything else?

Seems to be similar to https://github.com/winglang/wing/issues/2505
Also here's a thread in [slack](https://winglang.slack.com/archives/C047QFSUL5R/p1684328599195889?thread_ts=1684263632.536199&cid=C047QFSUL5R)

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by eladb**
Static namespaced methods, such as the ones vended as part of the Wing SDK have the form `namespace.Class.method()`. In order to be able to call this method we need to capture the class object at runtime (also known as the "inflight type").

Since this is a dot delimited string (`"namespace.Class"`), we need to mangle it in order to be able to pass it through the capture mechanism. So we represent these types as `"namespace_Class"` within the inflight code and then call `namespace.Class._toInflightType()` on the preflight side (which is how static methods are supported for non-namespaced types).

Then, we must add a `_toInflightType()` static method to `std` and `util` classes, which will `require()` the correct SDK javascript file and return the type itself. Added a test to make sure this is covered for future SDK classes.

### Resolves

* Fixes #2576

### Follow ups

* https://github.com/winglang/wing/issues/2782
* https://github.com/winglang/wing/issues/2785

### Misc

* Added `WING_TARGET` to cloud function environments (for all targets).
* Created an initial set of SDK tests for `std` types.
* Some renames in `jsify.rs` to normalize the mental model a little.
* Switch the implementation of `Boolean.fromJson` from a macro to an actual method (just for the fun of it).
* Reduced progress logs from `wing test` by default and add a `--progress` option to enable.
* Prelude: https://github.com/winglang/wing/pull/2799

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [x] Docs updated (only required for features)
- [x] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Comment by eladb** [comment]
@skorfmann fyi

**Comment by eladb** [comment]
@Chriscbr any feedback on this?

File: libs/wingc/src/jsify.rs [hunk 1]
```diff
@@ -1820,10 +1816,12 @@ impl<'a> CaptureScanner<'a> {
...
 	}
 
-	fn consider_reference(&mut self, path: &[&Symbol]) {
+	fn consider_reference(&mut self, path: &Vec<Symbol>) {
 		let fullname = path.iter().map(|s| s.name.clone()).collect_vec().join(".");
 
-		let lookup = self.current_env.lookup_nested(path, Some(self.current_index));
+		let lookup = self
+			.current_env
+			.lookup_nested(&path.iter().collect_vec(), Some(self.current_index));
```
Comment (yoav-steinberg) [inline libs/wingc/src/jsify.rs:1824]: `path` already a `&Vec`
```suggestion
			.lookup_nested(path, Some(self.current_index));
```

File: libs/wingc/src/jsify.rs [hunk 2]
```diff
@@ -907,28 +890,32 @@ impl<'a> JSifier<'a> {
 		let mut refs = self.find_inflight_references(class, &captured_vars);
 
 		// Get fields to be captured by resource's client
-		let captured_fields = self.get_capturable_field_names(class_type);
+		let lifted_fields = self.get_lifted_fields(class_type);
```
Comment (Chriscbr) [inline libs/wingc/src/jsify.rs:893]: Way better name, thank you

File: libs/wingsdk/src/std/bool.ts [hunk 3]
```diff
@@ -7,13 +8,22 @@ export class Boolean {
...
   public static fromJson(json: Json): boolean {
-    json;
-    throw new Error("Macro");
+    if (typeof json !== "boolean") {
+      throw new Error(
+        "unable to parse " + typeof json + " " + json + " as a boolean"
+      );
+    }
+    return JSON.parse(JSON.stringify(json));
+  }
```
Comment (Chriscbr) [inline libs/wingsdk/src/std/bool.ts:21]: Does this mean we can just get rid of macros? 👀  Big if true

File: libs/wingsdk/src/std/array.ts [hunk 4]
```diff
@@ -2,14 +2,22 @@
...
  * Immutable Array
  *
  * @typeparam T1
  */
 export class ImmutableArray {
+  /**
+   * @internal
+   */
+  public static _toInflightType(): Code {
+    return InflightClient.forType(__filename, "ImmutableArray");
```
Comment (yoav-steinberg) [inline libs/wingsdk/src/std/array.ts:18]: Looks like the 2nd arg here (`clientClass`) is always `this.name`. Is the extra arg here for extra flexibility?

File: libs/wingsdk/test/core/to-inflight-type.test.ts [hunk 5]
```diff
@@ -0,0 +1,46 @@
+import * as vm from "vm";
+import { test, assert } from "vitest";
+import * as std from "../../src/std";
+import * as util from "../../src/util";
+
+const skip = [
```
Comment (Chriscbr) [inline libs/wingsdk/test/core/to-inflight-type.test.ts:6]: Should these be TODOs of some kind? (not sure)

**Review by yoav-steinberg — APPROVED** [review]

File: libs/wingsdk/test/core/to-inflight-type.test.ts [hunk 6]
```diff
@@ -0,0 +1,46 @@
...
+  "std.Direction",
+  "std.T1",
+  "std.TEST_FQN",
```
Comment (Chriscbr) [inline libs/wingsdk/test/core/to-inflight-type.test.ts:9]: We could consider making this a static field on the `std.Test` class

File: libs/wingc/src/jsify.rs (hunk 1 above)
Comment (eladb) [reply libs/wingc/src/jsify.rs:1824]: I get:

```
mismatched types
expected reference `&[&ast::Symbol]`
   found reference `&Vec<ast::Symbol>`
```

File: examples/tests/sdk_tests/std/array.w
[the remark this answers is not in the document]
Comment (eladb) [reply examples/tests/sdk_tests/std/array.w:1]: what?

File: libs/wingsdk/src/std/array.ts (hunk 4 above)
Comment (eladb) [reply libs/wingsdk/src/std/array.ts:18]: TIL- DONE!

**Review by Chriscbr — APPROVED** [review]

File: apps/wing/src/util.ts [hunk 7]
```diff
@@ -19,6 +19,11 @@ export function normalPath(path: string) {
 }
 
 export async function withSpinner<T>(message: string, fn: () => Promise<T>): Promise<T> {
+  // if progress is disabled, just run the function
+  if (!process.env.PROGRESS) {
+    return fn();
+  }
```
[the remark this answers is not in the document]
Comment (eladb) [reply apps/wing/src/util.ts:25]: Let's discuss and extend this over a separate issue. My preference is to keep tools non-verbose unless requested, but I understand the need to add some progress info for long operations.

File: libs/wingsdk/src/std/bool.ts (hunk 3 above)
Comment (eladb) [reply libs/wingsdk/src/std/bool.ts:21]: I wouldn't get rid of them. They are a Good Thing™️ and required in order to "wrap" our primitives with Wing APIs. They are also a runtime optimization.

File: libs/wingc/src/jsify.rs (hunk 2 above)
Comment (eladb) [reply libs/wingc/src/jsify.rs:891]: Credits to @ekeren

File: apps/wing/src/cli.ts [hunk 8]
```diff
@@ -32,6 +32,10 @@ async function main() {
     process.env.DEBUG = "1";
   });
 
+  program.option("--progress", "Show compilation progress", () => {
+    process.env.PROGRESS = "1";
```
[the remark this answers is not in the document]
Comment (eladb) [reply apps/wing/src/cli.ts:36]: https://github.com/winglang/wing/issues/2800

File: libs/wingsdk/test/core/to-inflight-type.test.ts (hunk 5 above)
Comment (eladb) [reply libs/wingsdk/test/core/to-inflight-type.test.ts:6]: Mmm. not sure either. For now I think we are find because none of these have any static methods.

File: examples/tests/sdk_tests/std/array.w
[the remark this answers is not in the document]
Comment (yoav-steinberg) [reply examples/tests/sdk_tests/std/array.w:1]: The duplicate code in all these tests begs for having phase independent functions that can be called from both pre/inflight so we can test both phases without duplicating the code.

File: libs/wingc/src/jsify.rs (hunk 1 above)
Comment (yoav-steinberg) [reply libs/wingc/src/jsify.rs:1822]:
```suggestion
			.lookup_nested(path.as_slice(), Some(self.current_index));
```
