### PR TITLE
fix(compiler): missing diagnostics for preflight errors

### LINKED ISSUE #2410: JavaScript errors in preflight give no debugging information (regression)
### I tried this:

```js
bring cloud;

new cloud.Bucket();
new cloud.Bucket();
```

### This happened:

```
There is already a Construct with name 'cloud.Bucket' in $Root [Default]
```

(No line numbers or troubleshooting info)

### I expected this:

Some information about how to debug this problem. What line of code caused the problem, or how to get more debug information, etc.

In previous versions of the CLI it printed out a message like this:

Screenshot 2023-05-04 at 2 57 15 PM

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

0.15.13

### Wing Console Version

_No response_

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by attias**
Fixes #2410

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Review by eladb — APPROVED** [review]

File: apps/wing/src/commands/compile.ts [hunk 1]
```diff
@@ -234,40 +234,41 @@ export async function compile(entrypoint: string, options: CompileOptions): Prom
...
-            console.log("   " + chalk.dim(lines[i]));
-          }
+    output.push(chalk.red(`ERROR: ${e.message}`));
+
+    if ((e as any).stack && (e as any).stack.includes("evalmachine.<anonymous>:")) {
+      const lineNumber =
+        Number.parseInt((e as any).stack.split("evalmachine.<anonymous>:")[1].split(":")[0]) - 1;
+      
+      output.push('');
+      output.push(chalk.underline(chalk.dim(`${artifactPath}:${lineNumber}`)));
```
Comment (MarkMcCulloh) [inline apps/wing/src/commands/compile.ts:246]: Could this artifactPath instead be made relative to cwd?

Comment (staycoolcall911) [reply apps/wing/src/commands/compile.ts]: Done

**Review by eladb — APPROVED** [review]
