### PR TITLE
fix(vscode): vscode rename accidentally renames keyword arguments

### LINKED ISSUE #7016: VSCode rename accidentally renames keyword arguments
### I tried this:

See video.

### This happened:

https://github.com/user-attachments/assets/874cfe54-d944-4366-bef9-9a4e43b03303

### I expected this:

_No response_

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by tsuf239**
fixed #7016
and added tests :) 

@eladb FYI

## Checklist

- [ ] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [ ] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: packages/@winglang/wingc/src/lsp/rename_visitor.rs [hunk 1]
```diff
@@ -159,20 +161,48 @@ impl<'a> Visit<'a> for RenameVisitor<'a> {
...
+					for (field, ..) in fields {
+						self.add_reference_symbol(field, Some(&UnsafeRef::from(&c.env)));
+					}
+				}
 			}
-			.maybe_unwrap_option();
+			ExprKind::Call { arg_list, callee } => {
+				let Some(env) = self.ctx.current_env() else {
+					return;
+				};
```
Comment (Chriscbr) [inline packages/@winglang/wingc/src/lsp/rename_visitor.rs:183]: What does it mean if there isn't an env in this context? Can we add a comment?

**Review by Chriscbr — APPROVED** [review]
LGTM
