### PR TITLE
fix(console): preserve min and max zoom levels when running zoom to fit

### LINKED ISSUE #5530: Default zoom level in Wing Console is too big
### I tried this:

```js
bring cloud;

new cloud.Api();
```

### This happened:

image

### I expected this:

It's too big

### Is there a workaround?

_No response_

### Anything else?

_No response_

### Wing Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by skyrpex**
Fixes #5530.

### CODE REVIEW

File: apps/wing-console/console/ui/src/ui/zoom-pane.tsx [hunk 1]
```diff
@@ -60,7 +60,7 @@ const boundingBoxOverlap = (a: BoundingBox, b: BoundingBox) => {
     a.y + a.height > b.y
   );
 };
-const MIN_ZOOM_LEVEL = 0.125;
+const MIN_ZOOM_LEVEL = 0.25;
```
Comment (skyrpex) [inline apps/wing-console/console/ui/src/ui/zoom-pane.tsx:63]:
```suggestion
const MIN_ZOOM_LEVEL = 0.125;
```

**Review by eladb — APPROVED** [review]

**Review by ainvoner — APPROVED** [review]
