### PR TITLE
fix(vscode): util completions

### LINKED ISSUE #2888: Intellisense for util shows it contains only the Util class, not its members
### I tried this:

wrote this code:
```ts
bring util;
util.
```

### This happened:

Intellisesnse options where just `Util` the class.
If I then typed
```ts
util.Util.
```
then I got the autocomplete options for what the class contains

### I expected this:

see the autocomplete options for the Util class

### Is there a workaround?

writing 
```ts
util.Util.
```
will show the right autocomplete options.
The code will compile, but it is ugly and not a good experience.

### Component

IDE Extension

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

I think it is P1 since it is a day one experience and something that makes the language seem very immature

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
Fixes #2888

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/lsp/completions.rs [hunk 1]
```diff
@@ -300,12 +300,35 @@ fn get_completions_from_type(
...
 }
 
-fn get_completions_from_namespace(namespace: &UnsafeRef<Namespace>) -> Vec<CompletionItem> {
+fn get_completions_from_namespace(
+	namespace: &UnsafeRef<Namespace>,
+	current_phase: Option<Phase>,
+) -> Vec<CompletionItem> {
+	// If a namespace has a class named "Util", then its members can be accessed directly from
+	// the namespace as a syntactic sugar. e.g. "foo.bar()" is equivalent to "foo.Util.bar()"
+	let util_completions = match namespace.env.lookup_nested_str("Util", None) {
```
Comment (eladb) [inline libs/wingc/src/lsp/completions.rs:309]: Let's put this string in some const and reuse here and in the other place?
