### PR TITLE
fix: unable to resolve extern depending on cwd

### LINKED ISSUE #2081: Test fails when using external js file
### I tried this

```ts
bring cloud; 

resource NodeApi {
    extern "./nodeHelpers.js" static inflight _getEnvOrThrow(env_var_name:str): str;

    init() {}
}

new cloud.Function(inflight (e:str): str => {
    log("Hello world");
}, cloud.FunctionProps {
    env: {
      "API_URL": "HELLO",
    }
  }) as "test: use extern";
```

and the external file

```js
exports._getEnvOrThrow = (key) => {
  const value = process.env[key];
  if (!value) {
    throw new Error(`Missing environment variable: ${key}`);
  }
  return value;
};
```

### I expected this:

invoking with command `wing test <testfile>.w` works

### Instead, this happened

```bash
✖ Compiling to sim...
error: Failed to resolve extern "./nodeHelpers.js": Not Found
  --> extern.w:4:5
  |
4 |     extern "./nodeHelpers.js" static inflight _getEnvOrThrow(env_var_name:str): str;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Failed to resolve extern "./nodeHelpers.js": Not Found
```

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

0.11.0

### Wing Console Version

_No response_

### Node.js Version

v18.13.0

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #2081

When running wing from the same directory as the wing file, relative extern specs failed to be found in wingc. This was because the WASI preopens didn't understand the given absolute path when when trying to read the same directory as ".". To be completely honest, I'm not sure why it worked from a parent directory.

I added this test to apps/wing instead of hangar, and while I was there I changed it to use vitest instead of jest since the rest of our repo uses it.

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: apps/wing/src/wingc.ts [hunk 1]
```diff
@@ -95,6 +95,11 @@ export async function load(options: WingCompilerLoadOptions) {
     }
   }
 
+  // for each provided preopen, add resolved paths in case any absolute paths are used
+  for (const [key, value] of Object.entries(preopens)) {
+    preopens[normalPath(resolve(key))] = value;
+  }
```
Comment (MarkMcCulloh) [inline apps/wing/src/wingc.ts:101]: ℹ️ The actual fix

**Review by Chriscbr — APPROVED** [review]
Nice cleanup
