### PR TITLE
fix: language server completions are often inaccurate or irrelevant, no completions in type annotations

### LINKED ISSUE #2340: Type completions missing for variable type annotations
### I tried this:

```
bring cloud;

let x: cloud.
```

### This happened:

No completions shown

### I expected this:

Completions for types in the cloud namespace

### Is there a workaround?

No

### Component

IDE Extension

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #2760: Infinite dot notation in VS Code
### I tried this:

Used the dot notation to get suggestions from IntelliSense in VS Code.

wing-dot-notation-vscode

### This happened:

I could type an infinite amount of dots and still get IntelliSense suggestions nonetheless.

### I expected this:

I expected that, as per standard dot notation, a single dot would provide the suggestions and further dots would result in an error being thrown by the IDE.

### Is there a workaround?

_No response_

### Component

IDE Extension

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #2787: Completion inside function/variable declaration after colon - show all types
When I have a complete function declaration, this works: (notice there is a `=> {  } ` in this example )
image

But when I am implementing it, it doesn't:
image

```ts (wing)
let f = inflight (req: cloud.
//                           ^ should autocomplete 
````

### LINKED ISSUE #2863: Completion: fallback to no completion instead of a list of irrelevant global functions
### I tried this:

#2787 describes a completion case that should be solved on its own. 
However the current erroneous behavior should be fixed even before the issue is dealt with.

Completion in the VSCode ext. for this code:
```ts
let f = inflight (req: cloud.
```
shows a list of irrelevant global functions. We fallback to show these completions if we can't find others, but this behavior should be changed to show no completion instead.
image

### This happened:

image

### I expected this:

No completion at this point is better than irrelevant completion.

### Is there a workaround?

_No response_

### Component

IDE Extension

### Wing Version

0.19.4

### Wing Console Version

_No response_

### Node.js Version

19.3.0

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #3010: Autocomplete in the middle of namespace shows end of namespace completions
### I tried this:

```wing
bring "aws-cdk-lib" as awscdk;
awscdk.aws_lambda.
               //^ Auto-complete here show same options as
    //^ doing it here
```

### This happened:

[Screencast from 21-06-23 14:01:19.webm](https://github.com/winglang/wing/assets/1160578/2f4c3475-ba99-4f0d-87bb-a4c13d56c988)

### I expected this:

I expected the second autocomplete to show the sub-namespaces under `awscdk` and not the types inside `aws_lambda`. 

### Is there a workaround?

_No response_

### Component

IDE Extension

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #3083: VS code inflight snippet erases my init code
### I tried this:

Writing the initializer of my class

### This happened:

Screenshot 2023-06-26 at 11 04 56 AM

I started typing all of this code shown above on my keyboard - "c", "l", "a", ... up to "i", "n", "i", "t", "(", ")", <kbd>space</kbd>, "{". Then I tried pressing <kbd>enter</kbd> to open my init function. However, during that time the IDE auto-filled an "inflight () {}" snippet, so that when I pressed enter, I got this:

Screenshot 2023-06-26 at 11 07 09 AM

"init" is almost always the first piece of code I add to a class, so I run into this a few times a day.

### I expected this:

Pressing <kbd>enter</kbd> should take me to the next line:

Screenshot 2023-06-26 at 11 10 59 AM

### Is there a workaround?

Press <kbd>esc</kbd> right after you type "{" and before you press <kbd>enter</kbd>

### Component

IDE Extension

### Wing Version

0.22.2

### Wing Console Version

_No response_

### Node.js Version

18.14.1

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### LINKED ISSUE #3105: vscode: autocomplete should work with optional chaining `?.`
### I tried this:

```ts
bring cloud;

let j = Json {
  a: "a",
  b: {
    c: {
      n: 1
    }
  }
};

if let n = j.tryGet("a")?.
///                            ^ autocomplete
```

### This happened:

image

### I expected this:

to show me Json functions

### Is there a workaround?

_No response_

### Component

IDE Extension

### Wing Version

0.22.27

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #3010, Fixes #2760, Fixes #3105, Fixes #2787, Fixes #2863, Fixes #2340, Fixes #3083

https://github.com/winglang/wing/assets/1237390/35483238-fdab-4193-bba4-e88457be7b6d

This change includes pretty major changes to the completions module. The diff is especially messy due to many things being moved around. The existing completion tests were a lifesaver here.

I considered tackling https://github.com/winglang/wing/issues/2005 as well, but I wanted to fix the user experience before doing that improvement for contributors. So with that, it's important to note that **I'm still expecting a full rewrite of this module**. This PR was a really great learning experience to understand the problem space more.

### Improvements
- See the fixed issue list above; there are a lot!
- The main overall fix is that completions should show you irrelevant things way less often

### Misc
- Made sure the completion list is sorted so that it shows up in the same order that it would in the editor (via sort_text)
- Fixed panic in jsify when `x.b` is used inflight but x is an unexpected type (unresolved/function)
- Fixed panic when doing struct initialization with a non-struct (e.g. `NotRealType {}`)
- Pinned the version used for tree-sitter-cli used for the playground because there seem to be some issues upstream with the latest version. Does not seem to affect the wasm usage in rust.

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributing/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/lsp/completions.rs [hunk 1]
```diff
@@ -856,11 +873,64 @@ let j = MutJson {};
...
+	test_completion_list!(
+		inside_class_declaration_empty,
+		r#"
+class Foo {
+   
+//^
+}
+"#,
+		assert!(inside_class_declaration_empty.is_empty())
+	);
```
Comment (Chriscbr) [inline libs/wingc/src/lsp/completions.rs:894]: enhancement idea: We could give a hint for writing an init function. Also any accessor that's a valid to start a member/method declaration could be valid here (`inflight`, `static`, `pub`, etc.), though I'm not sure if other languages provide these kinds of completions in this spot or not

**Review by Chriscbr — APPROVED** [review]

File: libs/wingc/src/lsp/completions.rs (hunk 1 above)
Comment (MarkMcCulloh) [reply libs/wingc/src/lsp/completions.rs]: Totally, I think there is room for a few of them. I think most languages have them here.

I'll add the snippet for inflight here, but I'll hold off on other keywords for now since there is likely a more holistic change there (e.g. given a position, what keywords are valid)

**Review by eladb — COMMENTED** [review]
❤️
