### PR TITLE
fix(compiler)!: this.node and nodeof(this) have different behaviors

### LINKED ISSUE #5840: this.node and nodeof(this) give different behaviors
### I tried this:

```js
class A {
  new() {
    this.node.hidden; // type checking error
    nodeof(this).hidden; // OK
    
    log("root:   " + this.node.root.node.path);
    log("nodeof: " + nodeof(this).root.node.path);
  }
}

new A();

test "a" {
  assert(2 == 2);
}

test "b" {
  assert(2 != 3);
}

```

### This happened:

Two visible differences in behavior

1. We see `this.node` does not have a hidden field, but the node returned by `nodeof()` does
2. If we comment out the previous error and run the tests, we see the following is logged:

root:   root
nodeof: root/env0
root:   root
nodeof: root/env1

This shows the "root" values are different also.

### I expected this:

No difference / or only one of the syntaxes to be allowed

### Is there a workaround?

We recommend only using `nodeof(this)`

### Anything else?

`nodeof(this)` returns a special Node instance, not the `Node` instance that normally exists on classes from the [constructs](https://github.com/aws/constructs) framework. Some of the differences in behavior are because

Perhaps we can hide the node field from classes extending `Construct` somehow

### Wing Version

0.59.12

### Node.js Version

20.9.0

### Platform(s)

MacOS

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by Chriscbr**
To avoid confusion between different APIs and different runtime behavior between the `std.Node` and `constructs.Node` types, we avoid exposing `constructs.Node` in the language where possible.

Fixes #5840

BREAKING CHANGE: `.node` is no longer a directly available field on preflight classes and `IConstruct` values. Use the global function `nodeof()` for accessing tree nodes instead.

## Checklist

- [x] Title matches [Winglang's style guide](https://www.winglang.io/contributing/start-here/pull_requests#how-are-pull-request-titles-formatted)
- [x] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Wing Cloud Contribution License](https://github.com/winglang/wing/blob/main/CONTRIBUTION_LICENSE.md)*.

### CODE REVIEW

File: libs/wingc/src/type_check.rs [hunk 1]
```diff
@@ -1970,6 +1971,40 @@ impl<'a> TypeChecker<'a> {
...
+			.libraries
+			.lookup_nested_str(&CONSTRUCT_BASE_INTERFACE, None)
+			.expect("constructs.IConstruct not found in type system")
+			.0
+			.as_type()
+			.expect("constructs.IConstruct was found but it's not a type");
+		let iface = constructs_iface
+			.as_interface_mut()
+			.expect("constructs.IConstruct was found but it's not a class");
+		iface.env.symbol_map.remove("node");
```
Comment (eladb) [inline libs/wingc/src/type_check.rs:1992]: Maybe out `"node"` in a const

File: libs/wingc/src/type_check.rs [hunk 2]
```diff
@@ -1970,6 +1971,40 @@ impl<'a> TypeChecker<'a> {
...
+			.libraries
+			.lookup_nested_str(&CONSTRUCT_BASE_CLASS, None)
+			.expect("constructs.Construct not found in type system")
+			.0
+			.as_type()
+			.expect("constructs.Construct was found but it's not a type");
+		let class = constructs_class
+			.as_class_mut()
+			.expect("constructs.Construct was found but it's not a class");
+		class.env.symbol_map.remove("node");
```
Comment (eladb) [inline libs/wingc/src/type_check.rs:2005]: Ditto

File: libs/wingc/src/type_check.rs [hunk 3]
```diff
@@ -6805,14 +6845,19 @@ where
 	match lookup_result {
 		LookupResult::NotFound(s, maybe_t) => {
 			let message = if let Some(env_type) = maybe_t {
-				format!("Member \"{s}\" doesn't exist in \"{env_type}\"")
+				format!("Member \"{s}\" does not exist in \"{env_type}\"")
 			} else {
 				format!("Unknown symbol \"{s}\"")
 			};
+			let mut hints = vec![];
+			if s.name == "node" {
```
Comment (eladb) [inline libs/wingc/src/type_check.rs:6853]: Ditto

**Review by eladb — APPROVED** [review]
Yey!

File: libs/wingc/src/type_check.rs (hunk 1 above)
Comment (Chriscbr) [reply libs/wingc/src/type_check.rs]: Updated 👍
