### PR TITLE
fix(compiler): panic when adding field to interface

### LINKED ISSUE #2613: Panic during parsing: unexpected interface element node type `class_field`
### I tried this:

```js
interface Foo {
  bar: str;
}
```

### This happened:

```
thread '' panicked at 'Unexpected interface element node type class_field || {Node class_field (4, 2) - (4, 11)}', libs/wingc/src/parser.rs:691:21
stack backtrace:
RuntimeError: unreachable
    at std::panicking::rust_panic_with_hook::h911ba172265603df (wasm://wasm/009bb9ea:wasm-function[237]:0xdcb4a)
    at core::panicking::panic_fmt::h6958314cbbe045b2 (wasm://wasm/009bb9ea:wasm-function[1454]:0x184579)
    at  as core::iter::traits::iterator::Iterator>::try_fold::hb89a07c05f53fdae (wasm://wasm/009bb9ea:wasm-function[665]:0x150e7c)
    at  as alloc::vec::spec_from_iter::SpecFromIter>::from_iter::h69851a1a5d663434 (wasm://wasm/009bb9ea:wasm-function[447]:0x12784a)
    at wingc::parser::Parser::wingit::hdec3ecb17461246e (wasm://wasm/009bb9ea:wasm-function[149]:0xbbc50)
    at wingc_compile (wasm://wasm/009bb9ea:wasm-function[272]:0xe9c0e)
    at wingc_compile.command_export (wasm://wasm/009bb9ea:wasm-function[1600]:0x189aca)
    at Object.invoke ([/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/wingc.js:145:37](vscode://file//Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/wingc.js:145:37))
    at compile ([/Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/compile.js:125:38](vscode://file//Users/eladb/.volta/tools/image/packages/winglang/lib/node_modules/winglang/dist/commands/compile.js:125:38))
```

### I expected this:

To emit a non-panic diagnostics...

Seems like we don't have a good way to report diagnostics from our parser code, so all errors are panics.

### Is there a workaround?

Nope

### Component

Compiler

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

_No response_

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Fixes #2613

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/type_check.rs [hunk 1]
```diff
@@ -3496,7 +3496,7 @@ impl<'a> TypeChecker<'a> {
 		let parent_udt = parent_udt.unwrap();
 
 		if &parent_udt.root == name && parent_udt.fields.is_empty() {
-			self.spanned_error(parent_udt, format!("Class cannot extend itself"));
+			self.spanned_error(parent_udt, "Class cannot extend itself".to_string());
```
Comment (MarkMcCulloh) [inline libs/wingc/src/type_check.rs:3499]: The only reason I changed this is because clippy yelled at me about it

Comment (Chriscbr) [reply libs/wingc/src/type_check.rs:3499]: Weird it wasn't caught in CI in my PR

**Review by Chriscbr — APPROVED** [review]
