### PR TITLE
fix: hierarchal symbol lookups in language server sometimes fail

### LINKED ISSUE #1644: Memory corruption in SymbolEnv during post-compilation traversal
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

In the language server, we introspect Scopes and occasionally must do lookups in Symbol environment. As-is, this usually works fine.

This is a scenario that does not work:

```
if true {
  print("duh");
}
```

### I expected this:

`print` is defined at the root scope and is available in the inner scope. We should be able to lookup `print` in the inner env because the symbol is available there.

### Instead, this happened:

The data pointed to by env.parent had been lost, causing it to either be corrupted or gone. This causes lookups in the inner scope to be take a long time or occasionally panic.

### Component:

Compiler, IDE Extension

### Wing Version:

_No response_

### Node.js Version:

_No response_

### Platform(s):

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
Full credit to @yoav-steinberg for finding the root cause/solution.

While there is a more systemic issue at play here (the unsafe pointers), I would call this change a workaround rather than a hack (which is what I was doing before).

Fixes #1644

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

**Review by yoav-steinberg — APPROVED** [review]

File: libs/wingc/src/lsp/sync.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@ pub struct FileData {
 	/// The diagnostics returned by wingc
 	pub diagnostics: Diagnostics,
 	/// The top scope of the file
-	pub scope: Scope,
+	pub scope: Box<Scope>,
```
Comment (Chriscbr) [inline libs/wingc/src/lsp/sync.rs:23]: IIUC this might be a possible use case for `Pin<Box<Scope>>`

**Review by Chriscbr — APPROVED** [review]

File: libs/wingc/src/lsp/sync.rs (hunk 1 above)
Comment (yoav-steinberg) [reply libs/wingc/src/lsp/sync.rs:23]: I think you are right, but I suspect all our `UnsafeRef`s are a use case for `Pin<>` and I'm also not sure it'll compile since I don't think you can pin stuff in a `RefCell`. I'd prefer to just refactor everything to get rid of `UnsafeRef`, but not sure we have time for that now.
