### PR TITLE
fix(compiler): prevents a Json string variable from being stringified in a string interpolation

### LINKED ISSUE #3027: json string keys are extracted with extra `""`
### I tried this:

test on sim:
```
let obj = Json {"key": "val"};

let s = "path/with/${obj.get("key")}";
log(s);
```

### This happened:

printed: 
`path/with/"val"`

### I expected this:

to print: 
`path/with/val`

### Is there a workaround?

_No response_

### Component

Compiler

### Wing Version

_No response_

### Wing Console Version

_No response_

### Node.js Version

_No response_

### Platform(s)

MacOS

### Anything else?

_No response_

### Community Notes

* Please vote by adding a 👍 reaction to the issue to help us prioritize.
* If you are interested to work on this issue, please leave a comment.

### PR DESCRIPTION
**Pull request by marciocadev**
Closes #3027 

## Checklist

- [x] Title matches [Winglang's style guide](https://docs.winglang.io/contributors/pull_requests#how-are-pull-request-titles-formatted)
- [ ] Description explains motivation and solution
- [x] Tests added (always)
- [ ] Docs updated (only required for features)
- [ ] Added `pr/e2e-full` label if this feature requires end-to-end testing

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/jsify.rs [hunk 1]
```diff
@@ -348,7 +348,7 @@ impl<'a> JSifier<'a> {
 							InterpolatedStringPart::Expr(e) => {
 								match *self.get_expr_type(e) {
 									Type::Json | Type::MutJson => {
-										format!("${{JSON.stringify({}, null, 2)}}", self.jsify_expression(e, ctx))
+										format!("${{typeof {} === 'string' ? {} : JSON.stringify({}, null, 2)}}", self.jsify_expression(e, ctx), self.jsify_expression(e, ctx), self.jsify_expression(e, ctx))
```
Comment (eladb) [inline libs/wingc/src/jsify.rs:351]: Expressions run code. If the expression has side-effects, emitting it multiple times can be an issue. For example, if the expression is `doSomeCrazyExpensiveCalculation()` or `send1gOfDataToTheNetwork()`, we can't afford to call it multiple times.

An alternative approach would be to evaluate it only ones and then use it in the ternary.

Something like this:

```
((e) => typeof e === 'string' ? e : JSON.stringify(e, null, 2))({expr})
```

**Review by eladb — CHANGES_REQUESTED** [review]

**Review by eladb — APPROVED** [review]
