### PR TITLE
fix: panic while analyzing captures in unknown calls/news

### LINKED ISSUE #1647: wing panics on some cases of resources with nested identifier
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

`wing compile` this code:
```ts
resource SomeResource {
  init() {
  }

  inflight some_method() {
    some_var.some_method(some_var.some_prop);
  }
}
```
*this is a stripped-down version of [story-14](https://docs.winglang.io/contributors/rfcs/stories/story-14) which yields the same error message.

### I expected this:

To work.

### Instead, this happened:

Received the following error message:

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', libs/wingc/src/capture.rs:218:57
stack backtrace:
unreachable

### Component:

Compiler

### Wing Version:

0.5.67

### Node.js Version:

19.3.0

### Platform(s):

MacOS

### Anything else?

_No response_

### LINKED ISSUE #1747: Panic analyzing inflight when using `cloud` without `bring`
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```js
new cloud.Function(inflight () => { });
```

### I expected this:

To say `Unknown symbol "cloud"`

### Instead, this happened:

```
thread 'main' panicked at 'assertion failed: func_def.statements.env.borrow().is_some()', libs/wingc/src/capture.rs:92:17
```

### Component:

Compiler

### Wing Version:

_No response_

### Node.js Version:

_No response_

### Platform(s):

_No response_

### Anything else?

_No response_

### LINKED ISSUE #1802: Capture errors do not show red underline in IDE
### Community Note

> Please vote by adding a 👍 reaction to the issue to help us prioritize.
> If you are interested to work on this issue, please leave a comment.

### I tried this:

```
bring cloud;

let var x = 5;

let handler = inflight (m: str): str => {
    print("x: ${x}");
    //          ^ error: cannot capture reassignable variable "x"
};
```

### I expected this:

Expected a red squiggle to appear in VS code under "x" due to the error

### Instead, this happened:

The error only appears if I run `wing compile` directly or if I'm using the Wing console

### Component:

IDE Extension

### Wing Version:

0.5.126

### Node.js Version:

18.12.1

### Platform(s):

MacOS

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by MarkMcCulloh**
When type checking and coming across a bad (_read_: typed as `any`) call/new reference, we did not traverse the arguments. That means we never gave them type info. 
The capturing process (and lsp) assumes all expressions in the AST have a type, so it panics.

Also re-enabled vscode's capture diagnostics, because this bug is why I removed them in the first place.

Fixes #1747
Fixes #1647
Fixes #1802

*By submitting this pull request, I confirm that my contribution is made under the terms of the [Monada Contribution License](https://docs.winglang.io/terms-and-policies/contribution-license.html)*.

### CODE REVIEW

File: libs/wingc/src/type_check.rs [hunk 1]
```diff
@@ -1101,12 +1101,23 @@ impl<'a> TypeChecker<'a> {
...
+							self.type_check_exp(arg.1, env, statement_idx, context);
+						}
+
+						if matches!(t, Type::Anything) {
+							return self.types.anything();
+						} else {
+							return self.general_type_error(format!(
+								"Cannot create an instance of the type \"{}\"",
+								type_.to_string()
+							));
```
Comment (Chriscbr) [inline libs/wingc/src/type_check.rs:1119]: Can we add a test that shows this error?

**Review by Chriscbr — APPROVED** [review]
